### ISSUE TITLE
ViridisLite update causing downstream issues

### ISSUE THREAD

**Issue by tmerrittsmith** [thomasp85/ggraph#107]
I received the following error when trying to load ggraph:
```
Error: package or namespace load failed for ‘viridis’:
 object ‘cividis’ is not exported by 'namespace:viridisLite'
```
I think this is because viridis 0.5 depends on viridisLite 0.3.0, but ggraph only installs viridisLite 0.2.0.
See here: https://github.com/sjmgarnier/viridis/issues/52

It turns out that the issue can be solved by manually installing viridisLite, but I'm guessing there's a way to make this happen automagically in ggplot?

**Comment by thomasp85** [comment]
hmm... I think this problem occurs a bit down the stream, so to speak. `ggraph` does not use cividis (yet) so it might be some of the packages that `ggraph` depends on that throws the error?

**Comment by tmerrittsmith** [comment]
Yes the issue is when loading viridis rather than ggraph itself

**Comment by thomasp85** [comment]
I suspect you'll need to update viridisLite, but your issue is better posted on the relevant repositories...

**Comment by tmerrittsmith** [comment]
I presumed that since I didn't have viridis or viridisLite before installing ggraph, then somehow ggraph is referring to an older version of viridisLite? The manual fix worked as stated above.
