### ISSUE TITLE
Vignette code does not work

### ISSUE THREAD

**Issue by pgurazada** [thomasp85/ggraph#109]
library(tidygraph)
    library(ggraph)
    library(igraph)    

    wghtdgraph <- as_tbl_graph(data.frame(from = sample(5, 20, TRUE),
                                          to = sample(5, 20, TRUE),
                                          weight = runif(20)))

    ggraph(wghtdgraph, layout = 'fr') +
      geom_edge_link() +
      geom_node_point(aes(size = centrality_pagerank()))

    Error: This function should not be called directly

    graph <- create_notable('zachary') %>% 
      mutate(ranking = node_rank_leafsort())

    ggraph(graph, 'matrix') + 
      geom_edge_point(mirror = TRUE) + 
      theme_graph() + 
      coord_fixed()

    Error in layout_igraph_matrix(list(34, FALSE, c(1, 2, 3, 4, 5, 6, 7, 8,  : 
      could not find function "layout_igraph_matrix"

**Comment by thomasp85** [comment]
Try updating tidygraph

**Comment by pavanGurazada** [comment]
The following are the versions I have. Any specific dependencies I am missing?    

    other attached packages:
     [1] igraph_1.1.2                    ggraph_1.0.1                   
     [3] tidygraph_1.1.0

**Comment by fruchtblase** [comment]
I stumbled across the same error!
You can modify the code with with_graph() to make it run

```
ggraph(wghtdgraph, layout = 'fr') +
  geom_edge_link() +
  geom_node_point(aes(size = with_graph(wghtdgraph, centrality_pagerank())))
```

**Comment by pgurazada** [comment]
I am closing this issue but the error in the second part of the code still persists. Hopefully the doc will be fixed in due course.

**Comment by pgurazada** [comment]
Awesome package. Will explore more and leave pull requests where I can...
