### ISSUE TITLE
Can't set fixed color for edges with color =

### ISSUE THREAD

**Issue by dgrtwo** [thomasp85/ggraph#11]
Setting a color outside the `aes` doesn't work with `color = ` or `colour =`. Reproducible example:

``` r
library(dplyr)
library(igraph)
library(ggraph)

data_frame("a", "b") %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(color = "green")
#> Error: Unknown parameters: colour
```

This does work if I set it to `edge_colour` (not `colour`, or `edge_color`, which give similar errors). This makes some sense to me in that the fixed aesthetic names aren't expanded.

Note that the docs for the function say it's possible to set a fixed color with the `color =` argument:

> other arguments passed on to layer. There are three types of arguments you can use here:
>     * Aesthetics: to set an aesthetic to a fixed value, like color = "red" or size = 3.

**Comment by cashoes** [comment]
Also seems to be the case for size outside the `aes`:
`library(dplyr)
library(igraph)
library(ggraph)

data_frame("a", "b") %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(size = 3)
# Warning: Ignoring unknown parameters: edge_size
`

**Comment by thomasp85** [comment]
Edges doesn't have a size aesthetic - they have a width aesthetic
