### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by MarieS49** [thomasp85/ggraph#116]
Dear Thomas, 
I am sorry, maybe it is not the good place to write you this request but I do not find help however I post my problem on different forum. I think or I hope 

I can find solution with ggraph. I develop an app with shiny and I have a page where I plot a tree, a phylogenetic tree.  I have a data frame with the “position” of mutations, i.e. the branches where they should be. I would like to add points to my tree according to these mutations. I have different issues but it works only approximately. My real problem is that the points having the same parent and node information (i.e. the points supposed to be on the same branch) are not all represented, only one is, but not the others. I tried to put transparency as suggested with the help of the geom_point function to check if points are superimposed but no, there is indeed only one point. I join an example of my data and a plot for more clarity with my code ( cf PJ).
As you can see on line 1 and 4 of my data frame I have the same info, I hope to plot two points on the edge but I have only one, the point corresponding to the first line. Does anyone have any ideas or suggestions to help me?

As I can't fin issue with ggtree I tried to make a loop, I check geom_subview, I tried to plot my tree with plotly, I really search solutions before asking your help but I do not find any issue.
I am sorry I am beginner but really I cannot find issue. I will completely redraw my tree if I cannot find solution, maybe it is my only issue. 

Thank you so much 
Marie 

My basic code in R:

>  setwd("/home/marie/Dropbox/LIRMM/Script")
> 
> h = read.nexus("dating_phytime_tree.txt", tree.names = "tree 5", force.multi = TRUE)
> pp = maxCladeCred(h, tree = TRUE, part = NULL, rooted = TRUE)
> LeDataFrame = read.table("TableauTree.txt", header = TRUE, stringsAsFactors = FALSE)
> 
> 
> p <- ggtree(pp, mrsd = "0000-1-1" , alpha = 0.1, ladderize = FALSE) # mrsd permet de mettre le temps 0 comme temps recent
> p <- p + geom_tiplab() # ajoute les labels des feuilles 
> p <- p + geom_text2(aes(subset=!isTip, label = node), hjust = 1.3, vjust =-0.8,size = 2) # ajoute le numero du noeud
> p <- p + theme_tree2()
> p <- p + scale_x_continuous(minor_breaks = waiver(), limits = c(NA, 150), xlab("K Years"))
> p<- p %<+% subset(LeDataFrame, real_pos == 1) + geom_point(aes(x=branch, shape = edge_label, colour =factor(iteration), position = position_jitter(width =1, height = 0.1)) , alpha = 0.3,  na.rm = TRUE)
> plot(p)

[TableauTree.txt](https://github.com/thomasp85/ggraph/files/1806441/TableauTree.txt)
[Tree_Plot_malade.pdf](https://github.com/thomasp85/ggraph/files/1806442/Tree_Plot_malade.pdf)

My code in shiny:

> pTree <- reactive({
>       p <- ggtree(dataTree()) 
>       p <- p + theme_tree2() # ajoute l'echelle en dessous
>       p <- revts(p) # permet de mettre l echelle avec 0 comme temps recent
>       if (input$tipLabel == "Yes")
>       {
>         p <- p + geom_tiplab(align=TRUE) # ajoute les labels des feuilles 
>       }
>       if (input$nodeLabel == "Yes")
>       {
>         p <- p + geom_text2(aes(subset=!isTip, label = node), hjust = -0.3) # ajoute le numero du noeud
>       }
>       p <- p + scale_x_continuous(minor_breaks = waiver(), limits = c(NA, 50), xlab("K Years"))    
>   })
>  
>    output$Tree <- renderPlotly({
>      if (is.null(dataTree()))
>     {
>        paste("Please upload Nexus file")
>     }else{
>       ggplotly(
>         pTree())
>       }
>  })

**Comment by thomasp85** [comment]
Hi Marie

Is the attached plot the result you're aiming for or is it your current result you wish to improve?

**Comment by MarieS49** [comment]
Hi Thomas,

indeed it is my current result and not the result that I hope. I wish to improve a tree with for example on the edge between Marattia and the node 31 two points corresponding to the line 4 and 14 of my data frame "TableauTree.txt".

**Comment by thomasp85** [comment]
I'm sorry but I struggle to understand the data it seems to indicate that node 31 have multiple parents? This doens't seem tree-like?

Can you provide a reproducible example of the best you can get with ggraph? I'm not familiar with ggtree I cannot really understand your code...

**Comment by MarieS49** [comment]
Ok, I will try
