### ISSUE TITLE
problem when loading namespace

### ISSUE THREAD

**Issue by ramTT** [thomasp85/ggraph#118]
Hi!

I'm having some issues attaching ggraph. Installation seems to have worked, I've done the following:

#sudo apt-get -y install libcurl4-gnutls-dev
#sudo apt-get -y install libssl-dev
#install.packages("devtools")
#sudo apt-get install libudunits2-dev
# install.packages('udunits2', type = "source",
#                    configure.args=c('--with-udunits2-lib=/home/ramhak/R/x86_64-pc-linux-gnu-library/3.4'))
#devtools::install_github("thomasp85/ggraph", dependencies=TRUE, force=T)

However, when i run "library(ggraph)" I get:

Error: package or namespace load failed for ‘ggraph’:
 object 'scale_type' not found whilst loading namespace 'ggraph'

I'm running it on Ubuntu 16.04

Would really like to use your package!

Thanks in advance,
/R

**Comment by thomasp85** [comment]
This is because the development version of `ggraph` requires the development version of `ggplot2`

do `devtools::install_github('tidyverse/ggplot2')` and it should work

**Comment by ramTT** [comment]
Many thanks, worked perfectly! Keep up the great work!
