### ISSUE TITLE
Plot limits don't update when using large size of nodes

### ISSUE THREAD

**Issue by pierreroudier** [thomasp85/ggraph#125]
The limits of the plot produced by `ggraph` don't seem to update when using the `size` aesthetics of the nodes (and so the larger nodes appear "cut" by the border of the plot):

```
library(igraph)
library(ggraph)

m <- structure(c(0, 0.58, 0, 0.34, 0, NA, 0, 0, 0.12, 0, NA, NA, 0, 
0, 0.27, NA, NA, NA, 0, 0, NA, NA, NA, NA, 0), .Dim = c(5L, 5L
), .Dimnames = list(c("A", "B", "C", "D", "E"), c("A", "B", "C", 
"D", "E")))

diag(m) <- 0
ex_g <- graph.adjacency(m, mode = "lower", weighted = TRUE)
V(ex_g)$size <- c(4, 3.5, 3, 3, 2)
E(ex_g)$weight[is.na(E(ex_g)$weight)] <- 0

p_ex_graph <- ggraph(ex_g, layout = "igraph", algorithm = "fr", niter = 5000)

p_ex_graph + 
  geom_edge_link(aes(edge_width = weight), colour = "grey50", show.legend = FALSE) +
  geom_node_point(aes(size = size), fill = "grey70", colour = "grey10", show.legend = FALSE, shape = 21) +
  geom_node_text(aes(label = name)) +
  scale_size(range = c(6, 20)) +
  scale_edge_width_continuous(range = c(1, 3)) +
  theme_graph()
```
![rplot](https://user-images.githubusercontent.com/515259/39278423-20bb1ef4-4947-11e8-94ef-a51017bb59e8.png)

I've reproduced the problem on both the CRAN and the latest dev version.

**Comment by thomasp85** [comment]
This is more of an issue with ggplot2/grid. The node size does not affect the data range as it is just a glyph of absolute size. You can use the `expand` argument in `scale_x_*` and `scale_y_*` to get more room around your data...
