### ISSUE TITLE
ggraph doesn't respect color palettes for edges?

### ISSUE THREAD

**Issue by cboettig** [thomasp85/ggraph#129]
Possibly I'm just missing something obvious here.

Using the default hairball from the [Edges Vignette](https://cran.r-project.org/web/packages/ggraph/vignettes/Edges.html) here:

```r
ggraph(hairball, layout = 'kk') + 
  geom_node_point(aes(colour = pop_devel), size=3) +
  geom_edge_link(aes(colour = year)) + 
  ggthemes::scale_colour_ptol() 
```

I'm getting the pallette colors working for the nodes, but having no change on the edge colors: 

![ex](https://user-images.githubusercontent.com/222586/39770696-9ac73424-52a4-11e8-9796-21b4f563c57c.png)

What did I miss?  It would be great to be able to leverage the usual awesome `ggplot` palette stuff here. Thanks!

**Comment by thomasp85** [comment]
ggraph defines separate scales for nodes and edges. To modify edge scales use the full edge aesthetic names, e.g. `scale_edge_colour_brewer()`

**Comment by cboettig** [comment]
of course, that makes perfect sense. thanks!
