### ISSUE TITLE
Guess at default layouts

### ISSUE THREAD

**Issue by hadley** [thomasp85/ggraph#13]
So you can start with `ggraph(graph)`

**Comment by hadley** [comment]
Oh you just need `layout = nicely()` as the default?

**Comment by thomasp85** [comment]
I've contemplated about this and I'm frankly torn. On one hand the required call is currently a bit verbose, on the other hand I really dislike setting defaults for so important arguments. My main fear is that users would think the default is almost always the right choice (it almost never is) and never explore alternate layouts...

**Comment by hadley** [comment]
You could make it print a message? People tend to like quiet code so that would provide a (small) push to explore the options?

**Comment by thomasp85** [comment]
That might be a good idea...
