### ISSUE TITLE
Fr layout tree is always changing. How to make a tree to grow?

### ISSUE THREAD

**Issue by dkholo** [thomasp85/ggraph#130]
This is a follow up to issue #1. I need to be able to build a consecutive series of ggraphs that are growing so the older nodes remain in a certain position and we are able to observe the growth of the tree over time. Is this possible?
the code:
p<- ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n)) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name),size=4, vjust = 1.8, col = "red") +
  theme_void()+
  theme(plot.title = element_text(size=22, color="darkgrey"), plot.subtitle =element_text(size=14) ) +
  labs(title = "Title)", subtitle =label )
so far the tree changes too much.

in issue #1 you have mentioned fixed layout, but I am not sure how to apply it to the data set that changes so some branches can be fixed.

**Comment by dkholo** [comment]
I am trying to build the animation of the tree growing.

**Comment by ruaridhw** [comment]
I hope there's an easier way but here's how I would approach this...

As you've realised, Fruchterman Reingold is a stochastic layout which will return new positions every time it is called. The `create_layout` function is useful here as it means you can call it once and then reuse the node positions in subsequent plots. My approach would be to plot each of the "stages" of graph growth using a manual layout which just subsets the layout data frame to the points you need in that "stage".

You will need to provide your dataset in a reproducible manner to work with your exact case but here I have created a list of 4 graphs as `grow_graphs` where each graph is a subgraph of the next.

``` r
library(ggraph)
library(tidygraph)
library(igraph)
library(magrittr)

# Create a reproducible dataset
hs_graph <- as_tbl_graph(highschool)
grow_graphs <- lapply(1:4, function(x) make_ego_graph(hs_graph, order = x, nodes = 1) %>% extract2(1))
str(grow_graphs, 1) # List of 4 graphs
#> List of 4
#>  $ :List of 10
#>   ..- attr(*, "class")= chr "igraph"
#>  $ :List of 10
#>   ..- attr(*, "class")= chr "igraph"
#>  $ :List of 10
#>   ..- attr(*, "class")= chr "igraph"
#>  $ :List of 10
#>   ..- attr(*, "class")= chr "igraph"
```

Use `set.seed` to make the `fr` layout reproducible and call `create_layout` on the *largest* graph of the growth:
```r
set.seed(101)
final_layout <- create_layout(graph = grow_graphs[[4]], layout = "fr")
```

Finally, write a function which subsets each layout data frame and plot the graphs:
```r
get_graph_subset <- function(graph, layout) {
  # Use an ID to match vertices between graphs.
  # For this example graph, use the vertex attribute "name"
  vertices <- V(graph)$name
  subset(layout, name %in% vertices, x:y)
}

# Set the plot limits manually otherwise the x and y axes
# will be rescaled for each plot and the smaller graphs are zoomed
xmin <- min(final_layout$x)
xmax <- max(final_layout$x)
ymin <- min(final_layout$y)
ymax <- max(final_layout$y)

plot_graph <- function(graph) {
  graph %>%
    # Use the manual layout and subset final_layout data.frame
    ggraph(., layout = "manual", node.positions = get_graph_subset(., final_layout)) +
    geom_edge_link(alpha = 0.25) +
    theme_void() +
    # Force wide zoom for all plots
    expand_limits(x = c(xmin, xmax), y = c(ymin, ymax)) +
    # Add some colour according to stage which adds the nodes for the example graphs
    geom_node_point(aes(color = factor(distances(graph, to = 1))), size = 3) +
    scale_color_brewer(palette = "Set1", guide = "none") +
}

plot_graph(grow_graphs[[1]])
```

![](https://i.imgur.com/Yj6Wt9J.png)

``` r
plot_graph(grow_graphs[[2]])
```

![](https://i.imgur.com/FA9sX4D.png)

``` r
plot_graph(grow_graphs[[3]])
```

![](https://i.imgur.com/YZdkwFz.png)

``` r
plot_graph(grow_graphs[[4]])
```

![](https://i.imgur.com/YBIIxiW.png)

**Comment by dkholo** [comment]
Are there any other layouts that could be used to achieve a better result from the perspective of reducing the tree transformations?

**Comment by holgerbrandl** [comment]
Most likely the API has changed because the example provided by @ruaridhw now fails with 
```
Error in layout_fun(graph, circular = circular, ...) :
  unused argument (node.positions = subset(final_layout, name %in% V(.)$name, x:y))
```
Any ideas on how to fix that? The API docs seem to suggest to use `layout_tbl_graph_manual()` but I could not find a single usage example on the internet.

**Comment by thomasp85** [comment]
Specifying manual layouts is now much simpler. See `?ggraph` (in the development version)

**Comment by holgerbrandl** [comment]
I've tried the dev version. First, the `layout_tbl_graph_manual` is not exported when using 1.0.2.999 and second, in the docs of `ggraph` I could not find much more information than before (except for the pointer to `layout_tbl_graph_manual`)

**Comment by thomasp85** [comment]
No - the layout functions are not exported as they are not meant to be called directly, but only through `ggraph()` or `create_layout()`. There is still documentation for `layout_tbl_graph_manual()` though.

In the `ggraph` docs you'll find:
>Alternatively a matrix or a data.frame can be provided to the layout argument. In the former case the first column will be used as x coordinates and the second column will by used as y coordinates, further columns are dropped. In the latter case the data.frame is used as the layout table and must thus contain a numeric x and y column.

so you can simply do (based on the initial solution):

```r
plot_graph <- function(graph) {
  graph %>%
    # Pass node positions directly into layout
    ggraph(., layout = subset(final_layout, name %in% V(.)$name, x:y)) +
    geom_edge_link(alpha = 0.25) +
    theme_void() +
    # Force wide zoom for all plots
    expand_limits(x = c(xmin, xmax), y = c(ymin, ymax)) +
    # Add some colour according to stage which adds the nodes for the example graphs
    geom_node_point(aes(color = factor(distances(graph, to = 1))), size = 3) +
    scale_color_brewer(palette = "Set1", guide = "none")
}
```

**Comment by holgerbrandl** [comment]
Thanks for your patience and help. It works for me as suggested in your solution.
