### ISSUE TITLE
 non-numeric argument to binary operator

### ISSUE THREAD

**Issue by george-githinji** [thomasp85/ggraph#135]
Many thanks for this excellent package!! 
I have an issue whenever I call the arrow aesthetic with `geom_link`. 

`arrow = arrow(length = unit(4,'mm'), type = 'open'),end_cap = circle(5, 'mm'))
Error in y + r * sin(a * 2 * pi/360) : 
  non-numeric argument to binary operator`

This was not an issue previously and noticed the difference after updating the `ggraph `installation.

**Comment by thomasp85** [comment]
Can I get you to provide a complete reproducible example?

**Comment by thomasp85** [comment]
Closing as no reprex is provided
