### ISSUE TITLE
can't set fixed edge color ("colour" works)

### ISSUE THREAD

**Issue by wkc1986** [thomasp85/ggraph#137]
```
library(ggraph)
library(igraph)

g <- graph_from_data_frame(data.frame(seq(10), seq(10) + 2))
ggraph(g, "nicely") +
  geom_edge_link0(color = "blue") +
  geom_node_point()
```

`Warning: Ignoring unknown parameters: edge_color`

![rplot](https://user-images.githubusercontent.com/6200430/40505472-44785dbc-5f62-11e8-8050-737eeee9fde0.png)

**Comment by yiqinfu** [comment]
Can confirm this is still the case... "colour" works but "color" does not.
