### ISSUE TITLE
Summarise layouts in one place

### ISSUE THREAD

**Issue by hadley** [thomasp85/ggraph#14]
Current steps:

* `?ggraph`
* click `createLayout`
* click `layout_igraph_igraph`
* click `layout_`
* randomly click around see also, trying to find a layout that does what I want

**Comment by thomasp85** [comment]
Agree the current organisation is not ideal. Will happily take suggestions

**Comment by hadley** [comment]
I think in `?ggraph` the description of `layout` should be a bulleted list given the main layout functions , and then each of those topics should have a list summarising the main options.

**Comment by thomasp85** [comment]
I'm thinking of just merging the documentation for `graph` and `createLayout`. Wouldn't the "Details" section in `createLayout` fit your need?

Or are you missing a listing of all the layout algorithms supplied by igraph specifically?

**Comment by hadley** [comment]
Merging those two pages would be very helpful

**Comment by thomasp85** [comment]
Can you comment on whether the new setup improves your experience. Main differences is that `ggraph()` and `createLayout()` are documented on the same page along a list of all available layouts with links to their own doc page. Further the `layout_igraph_igraph()` page now includes a short description of all layouts provided by igraph along with links to their docs

**Comment by hadley** [comment]
Much better, thanks!
