### ISSUE TITLE
infinite arrows if ..index.. is used in edge aesthetic

### ISSUE THREAD

**Issue by fruchtblase** [thomasp85/ggraph#143]
If you use ..index.. in your edge aesthetic you don't get just one arrow at the end of your edge, but a lot of arrows at every point of the edge.

Here is a reproducible example 
`play_islands(5, 4, 1, 2) %>% 
  ggraph() +
  geom_node_point() +
  geom_edge_link(aes(alpha = 0.4),
                 arrow = arrow(length = unit(4, 'mm')), 
                 start_cap = circle(3, 'mm'),
                 end_cap = circle(3, 'mm'),
                 show.legend = F) +
  theme_graph()`

The result looks like this:
![bug_1](https://user-images.githubusercontent.com/10699549/41022615-685f42d8-696a-11e8-986b-b3b12ed02b38.png)

But the graph should look more like this:
![bug2](https://user-images.githubusercontent.com/10699549/41023042-93c65b72-696b-11e8-913f-eede99df6359.png)

|package   |*  |version    |date       |source                               |
|:---------|:--|:----------|:----------|:------------------------------------|
|ggraph    |*  |1.0.1.9999 |2018-05-31 |Github (thomasp85/ggraph@8d23845)    |
|igraph    |*  |1.2.1      |2018-03-10 |CRAN (R 3.4.4)                       |
|tidygraph |*  |1.0.0.9999 |2018-04-06 |Github (thomasp85/tidygraph@13e57b4) |

Hope this report is helpful! 
Kind regards

**Comment by thomasp85** [comment]
Indeed, this is a known issue with geom_path with varying aesthetics. I’m thinking of a better approach to arrows in general with more styles as well
