### ISSUE TITLE
edge labels not displayed

### ISSUE THREAD

**Issue by juliengrouillet** [thomasp85/ggraph#145]
Hi Thomas,

I noticed an odd behaviour when trying ggraph: edge labels are not displayed when I run the following code example (the rest of the graph is rendered as it should):

``` r
simple <- make_graph('bull')

V(simple)$name <- c('Thomas', 'Bob', 'Hadley', 'Winston', 'Baptiste')
E(simple)$type <- sample(c('friend', 'foe'), 5, TRUE)

ggraph(simple, layout = 'graphopt') + 
    geom_edge_link(aes(label = type), 
                   angle_calc = 'along',
                   label_dodge = unit(2.5, 'mm'),
                   arrow = arrow(length = unit(4, 'mm')), 
                   end_cap = circle(3, 'mm')) + 
    geom_node_point(size = 5)

```
I'm using ggplot2 ver 2.2.1.9000

Great package. I hope I can get passed that issue.

Cheers,

Julien

**Comment by malcolmbarrett** [comment]
I tried replicating this, but it works fine for me. Does it work under the ggplot2 3.0.0 update (on CRAN)?
