### ISSUE TITLE
angle not working for geom_node_label

### ISSUE THREAD

**Issue by xyx0** [thomasp85/ggraph#146]
I would like to rotate the labels, but it is not possible right now. For geom_node_text it is working fine.

```
library(ggraph)
graph <- graph_from_data_frame(flare$edges, vertices = flare$vertices)
ggraph(graph, 'dendrogram') + 
geom_node_label(aes( label=name , angle=90))+
geom_edge_diagonal()
```

**Comment by malcolmbarrett** [comment]
(FWIW, this is a gpplot2 problem, not a ggraph problem per se, as discussed [here](https://github.com/tidyverse/ggplot2/issues/2785))
