### ISSUE TITLE
Error loading ggraph package

### ISSUE THREAD

**Issue by mh47** [thomasp85/ggraph#147]
library(ggraph)
Error: package or namespace load failed for ‘ggraph’:
 object ‘scale_type’ is not exported by 'namespace:ggplot2'

**Comment by condwanaland** [comment]
Can you try updating `ggplot2` to the most recent version i.e.,

`install.packages("ggplot2")

**Comment by nick-youngblut** [comment]
I updated `ggplot2` to 3.0.0 and that fixed the issue.
