### ISSUE TITLE
Nodes cut - downsize the graph?

### ISSUE THREAD

**Issue by DominiqueMakowski** [thomasp85/ggraph#148]
I am using ggraph for visualizing correlations. Unfortunately, despite setting margins to 0 ( (`theme_graph(plot_margin = margin(0, 0, 0, 0))`), it still cuts the nodes at the extremities.

Example:
![correlations_mind](https://user-images.githubusercontent.com/8875533/42815145-d9fe9502-89c6-11e8-9ef1-1cc9ad073219.png)

Is there any way to "recentre" or downsize the graph a bit? (or move all nodes toward the graph centre)?

Thanks!

**Comment by malcolmbarrett** [comment]
In ggplot2 3.0.0, you can use the `expand_scale()` function.

``` r 
p +   
  scale_x_continuous(expand = expand_scale(c(.10, .10))) +
  scale_y_continuous(expand = expand_scale(c(.10, .10)))
```

**Comment by DominiqueMakowski** [comment]
@malcolmbarrett it works thanks!
