### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by SMRJensen** [thomasp85/ggraph#151]
Would it be possible to add any of the following suggested options to the ggraph package? (e.g. to the geom_conn_bundle function) To illustrate my suggestions I have made a few dummy plots. These plots represents a small dataset, where node sizes are scaled based on a given measured value for a parameter (values below a given threshold are excluded). Connections are scores of node correlations, where connections not showing significance are removed.

[Examples-of-new-ggplot-options.pdf](https://github.com/thomasp85/ggraph/files/2258778/Examples-of-new-ggplot-options.pdf)

Plot 1 from left:
Added features:	
•	Label-boxes that categorizes related notes, and node-labels of sub-groups within the categories. These are color coded to fit the group-coloring of the nodes.
•	Coloring of connections based on category-subgroups.
•	Scaling of connections based on a score.
•	A label that shows the corresponding values to the connection scale.
Plot 2 from left:
Added features:
•	Label-boxes with sub-group and category-groups reversed from the first plot, and color coded.
•	Connections color-scaled based on a score.
•	A label that shows the corresponding values to the connection-color.
Plot 3 from left:
Added features:
•	Analysis of specific node(s) of interest by emphasizing the connections through coloring connections, while deemphasizing other connections by coloring them a light grey. 
Thank you for your time.
Best Regards,
Stig

**Comment by thomasp85** [comment]
Thanks for the suggestions. Most of the features related to styling the edge connections should already be possible by passing along additional variables for the connections inside the `get_con()` function.

I've long wanted to have something akin to the category arcs you show and it may be added soon :-)
