### ISSUE TITLE
Cannot make a simple graph

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggraph#156]
While initially trying out `ggraph`, I encountered the following error:

``` r
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
library(ggraph)
#> Loading required package: ggplot2

ggraph(make_empty_graph(5) + edge(1, 2), layout="kk",
       aes(x=x, y=y)) +
  geom_point() + geom_line()
#> Warning in if (circular) {: the condition has length > 1 and only the first
#> element will be used
#> Error in if (circular) {: argument is not interpretable as logical
```

Created on 2018-09-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by billdenney** [comment]
At a quick glance, it appears that circular is an `uneval` instead of something evaluable as logical at https://github.com/thomasp85/ggraph/blob/8d23845eff968f131c3605a16e54cb38ff75f157/R/layout_igraph.R#L117

**Comment by malcolmbarrett** [comment]
You're using ggplot geoms instead of ggraph geoms. Try:

```
ggraph(make_empty_graph(5) + edge(1, 2), layout="kk") +
  geom_node_point() + geom_edge_link()
```

**Comment by malcolmbarrett** [comment]
More specifically, I think you're getting that error because `...` in ggraph passes to the layout function, not `ggplot()`, so the mapping argument `aes(x=x, y=y)` is being sent to the `circular` argument.

**Comment by billdenney** [comment]
Aha!  Thanks!  I was looking at one of the examples in the documentation and moved the `aes()` to the wrong part.  (I was wrong, not the documentation.)
