### ISSUE TITLE
Error with GeomEdgePath

### ISSUE THREAD

**Issue by akitepowell** [thomasp85/ggraph#16]
I'm not actually sure this is the right place to inquire about this error as it may be with ggproto instead.  Nevertheless, when running the code - 

word_cooccurences <- tokenize_df %>% pairwise_count(word,linenumber, sort=TRUE, upper = FALSE)
set.seed(1254)
word_cooccurences %>%
  filter(n >= 100) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr")+
  geom_edge_link(aes(edge_alpha = n, edge_width = n)) +
  geom_node_point(color = "darkslategray4", size = 3) +
  geom_node_text(aes(label = name), vjust = 2.5) +
  theme_void()

I get the error - 
Error: GeomEdgePath was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.

Will these be synced so that this works again?  Will this be fixed?
Thanks,
Aaron

**Comment by thomasp85** [comment]
Following the release of ggplot2 v2.2 all extension packages needs to be reinstalled, including ggraph
