### ISSUE TITLE
create_layout does not return the 3rd dimension ('z' column) when passing dim = 3

### ISSUE THREAD

**Issue by gsimchoni** [thomasp85/ggraph#160]
(Hi, this is a great package, thank you!)

The `dim` parameter in e.g. in `igraph::layout_with_fr` can be 2 or 3, in case a 3D layout is desired. The call:

```
layout3d <- create_layout(tidy_graph, layout = "fr", dim = 3)
```

passes without warning, and returns a data.frame with only the `x` and `y` columns, missing the `z` column.

I realize the source is somewhere here but it's out of my league:
https://github.com/thomasp85/ggraph/blob/8d23845eff968f131c3605a16e54cb38ff75f157/R/layout_igraph.R#L115

I think:
1. If because we're dealing with `ggplot2` philosophy this is intentional, there should at least be a warning, referring the user to use `igraph`.
2. But preferably I would change things so a 3D layout can actually be output from this function, i.e. including the `z` column.

Thanks.

**Comment by thomasp85** [comment]
You are correct that this is intentional due to the 2D nature of ggplot2 and a warning would probably be welcome
