### ISSUE TITLE
Feature Request: Automatically set start_cap and end_cap?

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggraph#162]
Again, thank you for the great tool!  `ggraph` has significantly simplified network visualization within my workflow.

I wonder if there is a reasonable way to automate the use of `start_cap` and `end_cap` (perhaps with a new argument `auto_cap=TRUE` or `start_cap="auto"` and `end_cap="auto"`)?  Specifically, I'm thinking of the following complexities:

* Detect if the nodes are plotted at all (if not, then it would default to no cap offset).
* Detect if only a single node geom is used, and if so, set the caps based on that node type and size.
* Detect if more than one node geom is used, and if so, set the caps based on the size of the largest node size (more precisely, the farthest away from the start and end of the line connecting the nodes or the loop start and end).

Given the need for this to detect aspects about other `geom`s, the solution may benefit from some generalization of the detection of other `geom`s needed in #157.

P.S. Given a suggestion of where to start, I could try for a PR.

**Comment by thomasp85** [comment]
This is not really possible as each layer lives completely separate from each other. There is no way an edge geom would know if any node geoms existed
