### ISSUE TITLE
graph font size

### ISSUE THREAD

**Issue by ETaSky** [thomasp85/ggraph#169]
Hello there! I am having an issue with the font size of node labels. I used theme_graph(base_size=7, base_family = "Arial") when creating the plot. But it seems the base_size adjustment is not working. The font size does not change whether or not I set the size.
After exporting as a pdf and open in Illustration, the font size indeed shows as 11.
My package versions are below:
 [1] ggthemes_4.0.1        ggraph_1.0.1.9999     networkD3_0.4        
 [4] bindrcpp_0.2.2        tidytree_0.2.1        ggtree_1.14.4        
 [7] data.tree_0.7.8       igraph_1.2.2          broom_0.5.1          
[10] ape_5.2               vegan_2.5-3           lattice_0.20-38      
[13] permute_0.9-4         conflicted_1.0.1.9000 ggrepel_0.8.0        
[16] extrafont_0.17        forcats_0.3.0         stringr_1.3.1        
[19] dplyr_0.7.8           purrr_0.2.5           readr_1.3.0          
[22] tidyr_0.8.2           tibble_1.4.2          ggplot2_3.1.0        
[25] tidyverse_1.2.1    

Thank you very much!
Jincheng

**Comment by thomasp85** [comment]
I'm afraid I can't reproduce this problem. Can I get you to post a reprex that shows that font size is not changed when changing `base_size`

**Comment by schochastics** [comment]
Coincidentally I noticed the same today. 
``` r
library(igraph)
library(ggraph)
library(graphlayouts)

g <- sample_gnp(20,0.3)

ggraph(g,layout = "stress")+
  geom_edge_link0()+
  geom_node_point(size=8,shape=21,fill="white")+
  geom_node_text(label=1:vcount(g))+
  theme_graph(base_family = "Arial",base_size = 12)+
  labs(title="test")
```

![](https://i.imgur.com/o8ZfGOK.png)

``` r
  

ggraph(g,layout = "stress")+
  geom_edge_link0()+
  geom_node_point(size=8,shape=21,fill="white")+
  geom_node_text(label=1:vcount(g))+
  theme_graph(base_family = "Arial",base_size = 24)+
  labs(title="test")
```

![](https://i.imgur.com/i7yRjXO.png)

Fix is to set the size in `geom_node_text` and increase the title_size parameter in `theme_graph`
``` r


ggraph(g,layout = "stress")+
  geom_edge_link0()+
  geom_node_point(size=8,shape=21,fill="white")+
  geom_node_text(label=1:vcount(g),size=8)+
  theme_graph(base_family = "Arial",title_size = 34)+
  labs(title="test")
```

![](https://i.imgur.com/dnw3pyV.png)

<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ETaSky** [comment]
Sorry, it has been too long ago and I don't even remember how this was an issue. Please feel free to close the thread.
