### ISSUE TITLE
Hasse diagram layout

### ISSUE THREAD

**Issue by alexpghayes** [thomasp85/ggraph#174]
http://mathworld.wolfram.com/HasseDiagram.html

In particular this would pave the way for utilities to turn `lme*` style model objects into Hasse diagrams.

**Comment by thomasp85** [comment]
Do you have any pointers to a good layout algorithm for this... it appears that optimal drawing of Hasse diagrams is a pretty tough problem... (btm, the underlying structure is just a DAG which can be shown with a sugiyama layout)

**Comment by alexpghayes** [comment]
Sadly not. However, my goal here would be to produce diagrams in style of http://users.stat.umn.edu/~gary/book/fcdae.pdf. Chapter 11 in particular describes how to make these diagrams.
