### ISSUE TITLE
Trouble installing ggraph

### ISSUE THREAD

**Issue by juliasilge** [thomasp85/ggraph#18]
I am having trouble installing the current version of ggraph (which is, sadly for us, meaning that @dgrtwo and I can't build our book at all right now). I get the following error both locally on Mac OS and on [Travis](https://travis-ci.org/dgrtwo/tidy-text-mining/builds/179631735) when trying to install ggraph:

```
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from '/private/var/folders/0w/prb4hnss2gn1p7y34qb2stw00000gp/T/Rtmp33Y2Ij/devtoolsea3d94ea05f/thomasp85-ggraph-cb08439/R':
  geom_edge_text.R
ERROR: unable to collate and parse R files for package ‘ggraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ggraph’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ggraph’
Error: Command failed (1)
```

I get this error both when installing ggraph after installing ggplot2 and ggforce from CRAN or from GitHub. I was able to build the book as of yesterday (I think?) so might this be a new problem?

**Comment by thomasp85** [comment]
This has been fixed now - sorry... I'm beginning to clean it up for a CRAN release, but I'll try to keep the master branch working :)

**Comment by juliasilge** [comment]
That is great! Having it on CRAN will be even better, of course. 😄

Thank you so much for your work on this great package.
