### ISSUE TITLE
Issue: Error in PathAttr

### ISSUE THREAD

**Issue by MichWeb75** [thomasp85/ggraph#190]
I run the sample code
```
library(ggraph)
library(igraph)
 graph <- graph_from_data_frame(highschool)
 
# Not specifying the layout - defaults to "auto"
ggraph(graph) + 
geom_edge_link(aes(colour = factor(year))) + 
geom_node_point()
```

Using `nicely` as default layout
Error in pathAttr(data, length(unique(data$group))) : 
  Not compatible with requested type: [type=character; target=integer].

RV 3.6.0
ggraph LATEST from devtools githutb

**Comment by mschubert** [comment]
For other people finding this via the search function:

This error also occurs with the current CRAN version of `ggraph` (`1.0.2`).

Fix is to install from `devtools::install_github("thomasp85/ggraph")` (or wait for the next release, I suppose)
