### ISSUE TITLE
R session crashes due to self-links

### ISSUE THREAD

**Issue by strohne** [thomasp85/ggraph#201]
First of all, thank you for this great package. I stumbled upon strange behavior: self-links in combination with start_cap/end_cap/arrow definitions occassionally crash the R session. Example:

```
library(igraph)
library(ggraph)

# This works
graph.nocrash <- make_graph(c(1,1,2,2,1,2), directed = T)
ggraph(graph.nocrash, layout = "circle") + 
  geom_node_point() +
  geom_edge_link(start_cap = circle(4,unit="mm"),
                 end_cap = circle(4,unit="mm"),
                 arrow = arrow(length = unit(4,"mm"))) 

# This crashes R, only difference is the order of edges in make_graph
graph.crash <- make_graph(c(1,1,1,2,2,2), directed = T)

ggraph(graph.crash, layout = "circle") + 
  geom_node_point() +
  geom_edge_link(start_cap = circle(4,unit="mm"),
                 end_cap = circle(4,unit="mm"),
                 arrow = arrow(length = unit(4,"mm"))) 
```

Sometimes it crashes not at first time, but at second. I guess this depends on the layout.

R version 3.5.3 
ggraph version 1.0.2
igraph version 1.2.4.1

**Comment by thomasp85** [comment]
Can I get you to upgrade to the GitHub version of ggraph and see if that resolves it? There has been numerous fixes in that area lately

**Comment by strohne** [comment]
@thomasp85 Yep, that solved the issue. Sorry, should habe tried this first.

**Comment by thomasp85** [comment]
No worries - the dev version will be released in a week or so but there won’t be any changes to what you just installed
