### ISSUE TITLE
start/end_cap not recognized as geometry in geom_edge_link2()

### ISSUE THREAD

**Issue by mjsmith037** [thomasp85/ggraph#205]
while 
`ggraph(play_erdos_renyi(10, 0.5)) + geom_edge_link(end_cap=circle())`
works as expected,
`ggraph(play_erdos_renyi(10, 0.5)) + geom_edge_link2(end_cap=circle())`
results in an error:
`Error in geo_type(ecap) : is.geometry(x) is not TRUE`

**Comment by thomasp85** [comment]
This has been fixed in devel which will soon be released
