### ISSUE TITLE
edge_alpha makes ggraph much slower

### ISSUE THREAD

**Issue by alexeilutay** [thomasp85/ggraph#206]
I built a graph G with 335 vertices and 934 edges (rds is attached as zip).
[G.zip](https://github.com/thomasp85/ggraph/files/3582438/G.zip)
_IGRAPH b2bb788 UNW- 335 934 -- 
attr: name (v/c), n.pubs (v/n), weight (e/n)_

With a code below I observed a dramatic increase in time when activated edge_alpha.
Without edge_alpha the performance time was 1.09 sec, while with edge_alpha time grew up to 26.47 sec!

`G %>% ggraph() + 

geom_edge_link0(edge_width = 0.2, edge_color = "grey50", **edge_alpha = 0.5**) +

geom_point(aes(x=x, y = y), size = 0.5)+ 

theme_graph()+

ggsave("graph.1.png", dpi=400,units="cm", width = 18,height = 10)`

Could you please advise if this is a bug or an inevitable property of ggplot graphics? Is there any way to work around this, I wonder.

**Comment by thomasp85** [comment]
This sounds more like a graphic device issue. Does the difference persist when using ragg?

**Comment by alexeilutay** [comment]
Thank you for advising {ragg}, I did not know about it. The problem disappeared, now it is 0.87 sec without _alpha_ and  0.97 with _alpha_. No more questions.
