### ISSUE TITLE
Hightlight one node

### ISSUE THREAD

**Issue by pwang16** [thomasp85/ggraph#209]
Hi Thomas,

I have one question: my network is very complicates containing so many nodes. If I want to highlight one node (Hub or keystone) on the top, not overlapped by other crowed nodes, how can I  bring this single trapped vertice front?

Thanks very much!

Peng

**Comment by thomasp85** [comment]
The easiest way is probably to add an additional node geom and then use the filter aesthetic to only include the node of interest

**Comment by pwang16** [comment]
Thank you so much Thomas for your reply! It works! I have another two questions, I appreacite it if you could give suggestions:
(1) how can I highlight the links of the node of interest, I want to highlight the links of the specific node, and bring all the links of this single trapped vertice to front too.
(2) How can I make the scale of the nodes in the legend as same level across two different networks. Since I made two networks, the node the size scale is different, it is hard to compare the node degree from two networks.

Thanks very much!
Have a great weekend!
Peng

**Comment by schochastics** [comment]
(1) same principle as for nodes
``` r
library(igraph)
library(ggraph)

g <- sample_gnp(20,0.2)
V(g)$name <- 1:20
vfocus <- 10
E(g)$efocus <- ends(g,E(g))[,1]==vfocus | ends(g,E(g))[,2]==vfocus
  
ggraph(g,"stress")+
  geom_edge_link(edge_colour = "grey66")+
  geom_edge_link(aes(filter = efocus), edge_colour = "red")+
  geom_node_point(shape = 21,fill = "grey25",size = 5)+
  geom_node_point(aes(filter = (name==vfocus)),shape = 21,fill = "red",size = 6)+
  theme_graph()
```

![](https://i.imgur.com/fkJk4st.png)

(2) normalize the degree in both networks by dividing with n-1 (n is number of nodes)
