### ISSUE TITLE
geom_node_circle doesn't recognize stroke aesthetic

### ISSUE THREAD

**Issue by emilydolson** [thomasp85/ggraph#210]
Thanks for writing such a wonderful package!

The documentation says that `geom_node_circle` accepts the `stroke` aesthetic, but when I try to use it (either inside `aes()` or outside it as a parameter) I get a warning that it is unrecognised ("Warning: Ignoring unknown parameters: stroke").

Example code that reproduces this problem:

```
graph <- as_tbl_graph(highschool) %>% 
    mutate(Popularity = centrality_degree(mode = 'in'))

# plot using ggraph
ggraph(graph, layout = 'kk') + 
    geom_edge_link() + 
    geom_node_circle(aes(r = Popularity/100), fill="blue", stroke=0)
```

**Comment by thomasp85** [comment]
Thanks. That is an error as there is no stroke aesthetic for circle nodes. Use the size and or linetype aesthetic to control the look of the stroke

**Comment by emilydolson** [comment]
Ah, great, thanks!
