### ISSUE TITLE
Documentation about manual layout

### ISSUE THREAD

**Issue by matteodefelice** [thomasp85/ggraph#212]
This question might appear as a lazy question but it's not. Yesterday I have spent a bit of time trying to understand how to position the nodes manually and the documentation did not really help me. Finally I have found [this closed issue](https://github.com/thomasp85/ggraph/issues/180) where @thomasp85 writes:

> Yeah, the manual layout specs have changed. You can just pass the matrix/data.frame directly to the layout argument in ggraph()

But yet I would like to know how to associate the coordinates to each node, in other words how to assign the right coordinates to the right nodes. Do I need to sort the coordinates according to the alphabetic order of the associated nodes? As far as I understand, the data frame that can be passed with the coordinates must contains only `x` and `y` as columns, and then how to specify the name of the node?

**Comment by thomasp85** [comment]
The order should simply match the order of the nodes in the graph you provide. ggraph does not reorder neither the graph nor the nodes (at least in manual layouts). You can also assign the coordinates to the nodes in the til_graph and then reference them directly:

```r
gr <- create_notable("bull") %>%
  mutate(x = runif(5), y = runif(5))

ggraph(gr, x = x, y = y) + 
  geom_edge_link() + 
  geom_node_point()
```

**Comment by matteodefelice** [comment]
Thanks, now it is more clear!
