### ISSUE TITLE
Change file download name

### ISSUE THREAD

**Issue by nschwamm** [thomasp85/ggraph#220]
Is there a way to change the file download name from "diagram" to a custom name?

To be more specific when you "download as png", the image that is created has the file name "diagram". That is what I would like to change.

Thanks!

**Comment by thomasp85** [comment]
I am not really sure what you are referring to? Where in ggraph can you "download as png"?

**Comment by nschwamm** [comment]
This is totally my mistake - meant to file under "ggiraph." I apologize!
