### ISSUE TITLE
Package("farver")  is needed to add into Imports packages.

### ISSUE THREAD

**Issue by TigerZhao007** [thomasp85/ggraph#221]
Otherwise users need to 
install.packages("farver")
library(farver)
manually.

See:
package or namespace load failed for ‘ggraph’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])

**Comment by thomasp85** [comment]
My guess is that you’ve updated scales and somehow that didn’t trigger an installation of farver. ggraph does not directly use farver and should this not import it
