### ISSUE TITLE
Any plans for extension like multinets?

### ISSUE THREAD

**Issue by hope-data-science** [thomasp85/ggraph#222]
Recently I have a need to draw a graph with multiple level. While always using tidygraph and ggraph, I can't find a direct implementation for data manipulation and visualization for multilevle graph data. Is there a way to include it? For your reference: <https://github.com/neylsoncrepalde/multinets>.

I am currently struggling to transfer my tidy code to make such visualization, if you have any suggestions, let me know. If I work it out, I'll post the codes as soon as possible. Thanks.

**Comment by thomasp85** [comment]
There is currently no dedicated support for multilevel networks in tidygraph or ggraph. My guess is that you can get by in ggraph (depending on what you want to achieve), by encoding successively stronger edge weights as you drill into levels, thus resulting in. a tighter within-level clustering in the final layout

**Comment by hope-data-science** [comment]
Thank you for the answer, my current scheme is to turn an tbl_graph object to a multilevel graph (in essence a bipartite simple graph in igraph), and use the visualization in multinets. Is there any convient way to construct bipartite graph using tidy data framework?

**Comment by hope-data-science** [comment]
For any tbl_graph, add type (lgl) column and use ` %>% add_layout_(as_bipartite()) -> graph_name ` could make it a bipartite simple graph. After that, just the codes in <https://github.com/neylsoncrepalde/multinets> could help the user with the rest.
