### ISSUE TITLE
Custom sizes and colors for nodes in circlpack layout

### ISSUE THREAD

**Issue by underbais** [thomasp85/ggraph#230]
Hi,

Having an igraph object (tbl_graph) how do I make nodes sized and colored with pre-defined sizes and colors (below)?

ggraph(tidy_tree, layout = 'circlepack') + 
  geom_node_circle() +
  theme_void()

> node_sizes
[1] 30.00000000  9.12942183  0.16883015  0.05513073  0.03187076  4.90354422  0.80153406 20.81378519 19.20983917
> rand_colors
[1] "#c66a19" "#20f98d" "#3c1d8c" "#f9564a" "#8803bc" "#ed821e" "#13b26b" "#c15234" "#ba0e1a"

Couldn't figure out playing with available options, sorry

Thank you!

**Comment by underbais** [comment]
Is this even possible within the package?

**Comment by thomasp85** [comment]
You can use the node sizes as weights in the circle packing algorithm, though only the lead nodes will be honoured. Colour can be set using the scale_fill_identity() scale

**Comment by underbais** [comment]
Actually, node sizes are rendered OK, but now the colors overlap i.e parental circles cover up the children. Is that what you mean by 'only the lead nodes will be honoured'?

**Comment by underbais** [comment]
`library(tidyverse)`
`library(igraph)`
`library(ggraph)`
`library(randomcoloR)`
`library(patchwork)`

`my_colors <- distinctColorPalette(k = length(my_vertices$name), altCol = FALSE, runTsne = FALSE)`

` depth_p <- ggraph(my_tree, layout = 'circlepack', weight = size) + `
              ` geom_node_circle(aes(fill=depth)) +`
              ` ggtitle(label = 'colors by depth') +`
              `theme_void() `

`custom_p <- ggraph(my_tree, layout = 'circlepack', weight = size) +`
`                geom_node_circle(aes(fill = my_colors)) + `
 `               ggtitle(label = 'custom colors (epic fail)') +`
`                theme_void()`

`depth_p + custom_p`

![image](https://user-images.githubusercontent.com/31751877/75586187-c1dbc100-5a41-11ea-85ed-7bdbb96147c1.png)

Looks like there is a layer issue (z-index) so that some circles cover others. Colors are distinct enough and circles have black borders so they should be displayed

Any way to fix this?

Thanks

**Comment by schochastics** [comment]
This is a dirty fix
``` r
library(igraph)
library(ggraph)

tidy_tree <- make_tree(9,3,"out")
V(tidy_tree)$col <- RColorBrewer::brewer.pal(9,"Set1")
V(tidy_tree)$ord <- 1:9
set.seed(12)
ggraph(tidy_tree, layout = 'circlepack',sort.by=ord) +
  geom_node_circle(aes(filter=ord==1,fill=I(col))) +
  geom_node_circle(aes(filter=ord!=1,fill=I(col))) +
  theme_graph()+
  coord_equal()
```

![](https://i.imgur.com/l4hUppS.png)

The problem is the order in which the nodes are drawn. With the filter argument, you get some level of control. (didnt include it, but for me green and blue are not visible if using `geom_node_circle()` without the filter.

**Comment by thomasp85** [comment]
The issue is that setting fill to a discrete variable will set the grouping aesthetic which governs the order of rendering. The easiest fix is to specify the grouping aesthetic explicitly:

``` r
library(tidygraph)
#> 
#> Attaching package: 'tidygraph'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(ggraph)
#> Loading required package: ggplot2

tidy_tree <- create_tree(9, 3, mode = "out") %>% 
  mutate(col = RColorBrewer::brewer.pal(9, "Set1"))

ggraph(tidy_tree, layout = 'circlepack') +
  geom_node_circle(aes(fill = col, group = depth)) +
  theme_graph()+
  coord_equal()
```

![](https://i.imgur.com/6IqUKeL.png)

<sup>Created on 2020-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dawidgnowak** [comment]
Hi,

I was wondering if you have different groups and subgroups giving in total 100% but different proportions. Would you expect all circles  be the same size? I made an example and I see different sizes. Is it possible to scale them to have the same area? I tried to adjust number to area or radius but still was seeing different sizes of circles.

Thanks,
Dawid

```
# libraries
library(ggraph)
library(igraph)
library(tidyverse)
library(packcircles)

# example tibble
tdf <- tibble(day_code=factor(c("root", "root", "root", "root", "PRL","PRL","PRL","LVR","LVR", "LVR", "BLD", "BLD", "BLD", "AAA", "AAA")),    
                day_code_seq=factor(c("PRL", "LVR", "BLD", "AAA", "PRL.CU01","PRL.CU02","PRL.CU03","LVR.CU01","LVR.CU02","LVR.CU03", "BLD.CU01", "BLD.CU02", "BLD.CU03", "AAA.CU01", "AAA.CU02")), 
                perc=as.numeric(c(0, 0, 0, 0, 50, 25, 25, 5, 55, 40, 75, 5, 20, 98, 2)),
                seq = factor(c("PRL", "LVR", "BLD", "AAA", "CU01","CU02","CU03","CU01","CU02", "CU03", "CU01", "CU02", "CU03", "CU01", "CU02")))

# scale based on radius -> no change
#tdf$perc <- pull(circleProgressiveLayout(tdf$perc, sizetype="radius")[3])
# scale based on area 
#tdf$perc <- pull(circleProgressiveLayout(tdf$perc, sizetype="area")[3])

# replace NA with 0
tdf <- 
  tdf %>% 
  replace(is.na(.), 0)

# create a dataframe with the nodes attributes
nodes <- 
  tdf %>% 
  distinct(day_code_seq, perc, seq) %>% 
  add_row(day_code_seq = factor("root"), perc = 0, seq = factor("root")) # create the highest level -> root

# make a graph from data frame
graph <- graph_from_data_frame(tdf, vertices = nodes)

# plot
pdf("~/Desktop/circle_graph.pdf", 10, 10)
circle_graph <- 
  ggraph(graph, layout = "circlepack", weight = perc) + 
  geom_node_circle(aes(fill=depth)) +
  geom_text(aes(x = x, y = y, label = perc)) +
  coord_fixed()
# theme
circle_graph + theme_void() + theme(legend.position="none") 
dev.off()
```

[area_circle_graph.pdf](https://github.com/thomasp85/ggraph/files/5533903/area_circle_graph.pdf)
[radius_circle_graph.pdf](https://github.com/thomasp85/ggraph/files/5533904/radius_circle_graph.pdf)

**Comment by thomasp85** [comment]
This does no seem related to the issue - please open a new issue for new questions/bugs
