### ISSUE TITLE
bug using x as label name

### ISSUE THREAD

**Issue by JanaJarecki** [thomasp85/ggraph#232]
Hi,
I believe I found a bug, if I specify node labels as a, b, c but the variable holding the labels is called  `x`, the labelling fails. If the variable is called `xx` it works.

    library(tidygraph)
    library(ggraph)
    gr <- create_complete(3) %>%
      activate(nodes) %>%
      mutate(x = sample(c('a', 'b'), 3, TRUE))

    ggraph(gr, layout = "kk") + 
      geom_edge_fan() + 
      geom_node_text(aes(label = x))

**Comment by mbojan** [comment]
I believe that ggraph uses node variables `x` and `y` internally for node positions when plotting. Your `x` will be overwritten by `ggraph`.

Perhaps it is not so much of a bug but a lack of documentation that  `x` are `y` are interpreted specially. It may even be a feature, because you can use the coordinates when plotting:

```r
ggraph(gr, layout = "kk") + 
  geom_edge_fan() + 
  geom_node_text(aes(label = paste0("(", x, ", ", y, ")")))
```

**Comment by JanaJarecki** [comment]
@mbohjan: I know I have the same issue in my own package with internally used names.

Seems, from a software-design standpoint, not desired to restrict the set of allowed variable names by design -- this defies the idea of the flexibility that we want using aes(label = variable).

Ideas
- usage `.x` and `.y` internally (much less likely to be used as columns in data)
- usage of a friendly warning
- renaming the layout columns given that they exist in the data

I am sorry @thomasp85 that I cannot look at the code myself and do a PR but where I research the semester just started last week i.e. I am swamped. :( Sorry.
