### ISSUE TITLE
layout fabric, label nodes at end of node

### ISSUE THREAD

**Issue by Gibbsdavidl** [thomasp85/ggraph#233]
Hey there,
Thanks for the great package!

I'm really wishing I could place the node labels at the end of the horizontal-node-line for fabric layouts, instead of the label being placed in the middle of the node-line.

Is that possible?

ggraph(g, layout='fabric', sort.by = node_rank_fabric()) + 
  geom_node_range(colour = 'grey') + 
  geom_edge_span(end_shape = 'square', edge_width=1.5, mapping = aes(colour=S1)) +
  scale_edge_colour_viridis() +
  theme_graph() +
  geom_node_label(aes(label = name))

<img width="539" alt="Capture" src="https://user-images.githubusercontent.com/561865/75733612-a9baaa80-5caa-11ea-951d-fb776293f6dd.PNG">

**Comment by thomasp85** [comment]
You can move the label to the side by setting `x` to `xmin` (and setting some additional arguments to make it look good for longer names):

```r
ggraph(g, layout='fabric', sort.by = node_rank_fabric()) +
  geom_node_range(colour = 'grey') +
  geom_edge_span(end_shape = 'square', edge_width=1.5, mapping = aes(colour=S1)) +
  scale_edge_colour_viridis() +
  theme_graph() +
  geom_node_label(aes(x = xmin, label = name), hjust = 1, nudge_x = -1)
```

**Comment by aourednik** [comment]
Could this be the default node_label position in fabric layout, or be documented directly in [an example on the layout_tbl_graph_fabric docs page here](https://ggraph.data-imaginist.com/reference/layout_tbl_graph_fabric.html) ? I had the same question and found the answer burried deep in this github issues page.

The [RBioFabric](https://github.com/wjrl/RBioFabric) implementation yields this; I think that is what most users expect:

```{r}
bioFabric(g.top.weightOver5 %>% slice(1:20))
```

![image](https://user-images.githubusercontent.com/7204421/153010758-2eb0d56f-613c-4871-be5f-3efa803dfd95.png)

@wjrl :The big issue with the RBioFabric implementation is that most labels are so small that it becomes impossible to read them. But it conveniently repeats labels above each group of edges emanating from a single node. 
Also, it _colors all edges by the color of the outgoing node_ (this makes most sense among all other colouring options). Could one steer the size of the labels, somehow?
 
@thomasp85: 
1. How can one place a second label above  each group of edges emanating from a single node?
2. Could not geom_edge_span(aes(color=group)) take the "group" variable from each outgoing node? I understand this might be confusiong to have a node variable in an edge aestehtic, but in this case, it would make sense. 

The best I got in the ggraph implementation of biofabric is this:

```
ggraph(g.top.weightOver5 %>% slice(1:20),layout="fabric", sort.by=node_rank_fabric()) + 
	geom_node_range(aes(colour=group),show.legend = F) +
	geom_edge_span(end_shape = "circle") +
	geom_node_label(aes(x=xmin-5,label=name, color=group),show.legend = F)
```

![image](https://user-images.githubusercontent.com/7204421/153015680-09e7e280-c99b-4a0b-99ea-345d3c36c7b2.png)
