### ISSUE TITLE
plot multiple edge elements of the same type

### ISSUE THREAD

**Issue by kdome** [thomasp85/ggraph#236]
Currently if I (try to) add another type of edges on the same nodeset, stored in a different object, it only plots the first. It doesn't throw an error, however.
e.g. if I have a friendship network and an animosity network stored in separate igraph objects.

`ggplot(friendgraph)+ 
geom_node_point()+  
geom_edge_link(colour = "black")+  
geom_edge_link(E(enemygraph)$vnames, colour = "red")+  
theme_graph`

**Comment by thomasp85** [comment]
Please read the introduction vignettes in ggraph. You cannot use the package in this way
