### ISSUE TITLE
trying to fill each circle with a manually specified color of vertex attribute

### ISSUE THREAD

**Issue by antonkratz** [thomasp85/ggraph#237]
I am trying to represent a graph as a circle packing plot using R / igraph / ggraph:
```
    df <- read.table("elist.txt", header=F, sep="\t")
    df2 <- read.table("vlist.txt", header=F, sep="\t")
    mygraph <- graph_from_data_frame(df, vertices=df2)
    ggraph(mygraph, layout = 'circlepack') + geom_node_circle() +
      geom_node_text(aes(label=as.character(name))) + coord_fixed()


```
This works. But I want each node to be filled in a color which I specified as a vertex attribute of `mygraph`. So I am trying to do s/th like:
```
geom_node_circle(aes(fill=V2))
```
With incomprehensible results.

How can I solve this? I am trying to fill each circle with a manually specified color, where color is either a name as a string (or even better would be a hex code).

[elist.txt](https://github.com/thomasp85/ggraph/files/4346288/elist.txt)
[vlist.txt](https://github.com/thomasp85/ggraph/files/4346289/vlist.txt)

**Comment by thomasp85** [comment]
Use `scale_fill_identity()`
