### ISSUE TITLE
Feature request: double-headed (bidirectional) arrows

### ISSUE THREAD

**Issue by vankesteren** [thomasp85/ggraph#240]
For some applications, it is useful to have bidirectional arrows. Maybe the `arrow` argument can turn into an `arrow_end` and `arrow_start` argument?

I'm trying to create simple graph visualisations of structural equation models from a fitted `lavaan` object like so:
![image](https://user-images.githubusercontent.com/11596858/78164897-cd5c4680-744a-11ea-804e-2ebeea8c98a5.png)

`ggraph` seems like a really good choice for this! It's already looking quite good with the "tree" layout and the parameter estimates for this model in there!

![image](https://user-images.githubusercontent.com/11596858/78165283-612e1280-744b-11ea-8dec-2ef85fce4388.png)

I intend to make layout functions for the most common types of models. The only missing part (to my knowledge) is double-headed arrows.

**Comment by malcolmbarrett** [comment]
grid can already draw double-headed arrows. In the `arrow` argument, use `grid::arrow()` with the argument `ends = "both"`

**Comment by vankesteren** [comment]
Oh man, such a simple fix! thanks!
