### ISSUE TITLE
Position of fork points in tree

### ISSUE THREAD

**Issue by romanhaa** [thomasp85/ggraph#241]
Hi Thomas,

In my Shiny app I draw phylogenetic trees and currently use the `ggtree` package to do so. During your last YouTube workshop I realised that I could do the same with `ggraph` and so I tried to reproduce the trees I already had. 

This is the data, it's of class `phylo`.

```r
data$clusters$tree
# Phylogenetic tree with 16 tips and 15 internal nodes.
# Tip labels:
#	1, 2, 3, 4, 5, 6, ...
# Rooted; includes branch lengths.

str(data$clusters$tree)
# List of 4
#  $ edge       : int [1:30, 1:2] 17 17 18 18 19 20 20 25 26 26 ...
#  $ edge.length: num [1:30] 35.41 8.76 26.64 4.21 8.87 ...
#  $ tip.label  : chr [1:16] "1" "2" "3" "4" ...
#  $ Nnode      : int 15
#  - attr(*, "class")= chr "phylo"
#  - attr(*, "order")= chr "cladewise"
```

This is the result when I draw it with `ggtree`, the reference:

```r
tree <- data$clusters$tree
tree$tip.label <- paste0("Cluster ", tree$tip.label)
ggtree(tree, aes(x, y)) +
  scale_y_reverse() +
  ggtree::geom_tree() +
  ggtree::theme_tree() +
  ggtree::geom_tiplab(offset = 1) +
  ggtree::geom_tippoint(color = data$clusters$colors, shape = 16, size = 5) +
  coord_cartesian(clip = 'off') +
  theme(plot.margin = unit(c(0,2.5,0,0), 'cm'))
```

![image](https://user-images.githubusercontent.com/18103560/78530619-4ad5dd00-77e4-11ea-87b1-f2e1f737f0bb.png)

First of all, I noticed that I have to convert the `phylo` object to `dendrogram` with the `phylogram::as.dendrogram.phylo()` function because otherwise I didn't manage to only label the tips, but that's another discussion. Here is the result of `ggraph`:

```r
ggraph(phylogram::as.dendrogram.phylo(data$clusters$tree), layout = 'dendrogram') +
  geom_edge_elbow() +
  geom_node_point(aes(filter = leaf, color = label), size = 5) +
  geom_node_text(aes(filter = leaf, label = paste0('Cluster ', label)), hjust = 0, nudge_y = 0.25) +
  coord_flip(clip = 'off') +
  scale_x_reverse() +
  scale_y_reverse() +
  scale_color_manual(values = data$clusters$colors) +
  theme_void() +
  theme(
    legend.position = 'none',
    plot.margin = unit(c(0,2.5,0,0), 'cm')
  )
```

![image](https://user-images.githubusercontent.com/18103560/78530768-8e304b80-77e4-11ea-9651-00c8362cf64e.png)

Notice how the fork points are at different X positions. I'd appreciate your feedback as to whether it's possible to reproduce the behaviour in `ggtree`.

Cheers,
Roman

**Comment by thomasp85** [comment]
you can set the `height` argument to `height` in the dendrogram layout (`ggraph(tree, layout = 'dendrogram', height = height) + ...`
