### ISSUE TITLE
Weight must be numeric error - for a .csv file

### ISSUE THREAD

**Issue by ishwari-siva** [thomasp85/ggraph#244]
Hi!
I am trying to create a circular graph with ggraph(layout='circlepack'.....). I get a 'weight must be numeric error' when I create a dataframe from an imported csv file. 

The solution given for issue #231 i.e. use unquoted input, works (in my case) only if the dataframe was created manually. So, it works in the case of the example given below (taken from stackoverflow). 

```
`library(ggraph)
library(igraph)
library(dplyr)


df <- data.frame(group=c("root", "root", "a","a","b","b","b"),    
                 subitem=c("a", "b", "x","y","z","u","v"), 
                 size=c(0, 0, 6,2,3,2,5))

# create a dataframe with the vertices' attributes

vertices <- df %>% 
  distinct(subitem, size) %>% 
  add_row(subitem = "root", size = 0)

graph <- graph_from_data_frame(df, vertices = vertices)

ggraph(graph, layout = "circlepack", weight = 'size') + 
  geom_node_circle(aes(fill =depth)) +
# adding geom_text to see which circle is which node 
  geom_text(aes(x = x, y = y, label = paste(name, "size=", size))) +
  coord_fixed()`

#'
```

The only thing I do differently is use "read.csv" to read my file, and then use "as.dataframe()"  to convert to the csv data to a dataframe. When I use this new dataframe to create the circular plot I get an error. Can you help me?

I have attached the file as well.
[CSV_ggraph_weights error.zip](https://github.com/thomasp85/ggraph/files/4540927/CSV_ggraph_weights.error.zip)

**Comment by thomasp85** [comment]
My guess is that the column you want to use for weight have been converted to a character or factor vector during import

**Comment by ishwari-siva** [comment]
No. I tried converting it to integer, splitting it into vectors and creating the dataframe, I even tried all the steps in an Ubuntu and Windows OS, and I get the same error. I am stumped. I import csv files and use igraph, ggplot2 and other packages, and haven't run into this issue. 

If I unquote the weight field, the error I get: Error in tree_to_hierarchy(graph,direction, sort.by, weight): Leafs must have weight

If I quote the weight field: Error in tree_to_hierarchy(graph,direction, sort.by, weight): weight must be numeric.

**Comment by thomasp85** [comment]
Have you checked that the column is indeed numeric before plotting it? If not, then it is an issue in you import flow, not in ggraph
