### ISSUE TITLE
How to correctly facet nodes and edges using ggraph?

### ISSUE THREAD

**Issue by IlariaMarina** [thomasp85/ggraph#251]
Hi all, I am trying to run in R a network analysis comparing 2 different conditions (A and B) which share some vertices.
I generated vertices and edges data frames:

```
vertices<-data.frame(marker = c("CD3", "CD25", "pCREB", "CD4", "pSTAT5", "pS6", "pRB",  "CD25", "CD3", "pSTAT4"),
cond_1 = c("A", "A", "A", "A", "B", "B", "B", "B", "B", "B"),
EMD= c(-0.83, -1.43, -0.07, -1.16, 0.08, 0.16, 0.28, 1.83,-0.37, 0.12 )
)
edges<-data.frame(marker_x = c("CD3","CD3", "CD4", "pSTAT5", "pRB", "CD25", "CD3"),
                  marker_y = c("CD25", "pCREB", "CD25", "pS6", "pS6", "pS6", "pSTAT4"),
                  cond_1 = c("A", "A", "A", "B", "B", "B", "B"),
                  DREMI=c(0.53, 0.80, 0.7, 1, 0.35,0.24, 0.44)
)
```
Then I used tidygraph and ggraph to run the network analysis faceting by edges and nodes and colouring edges and vertices according to the values stored in DREMI or EMD columns, respectively:

```
library(tidygraph)
    net.tidy <- tbl_graph(
      nodes = vertices, edges = edges, directed = TRUE
      )
    library(ggraph)
    ggraph(net.tidy, layout="fr") + 
      geom_node_point(aes(fill=EMD), shape=21, alpha = 0.4,size=8, repel=TRUE) +
      geom_node_text(aes(label = marker), repel=TRUE) +
      geom_edge_link(aes(color=DREMI), arrow = arrow(length = unit(4, 'mm')), 
                     end_cap = circle(1, 'mm'))+
      scale_fill_gradientn(colours = colorRampPalette((brewer.pal(n = 9, name = "Reds")))(50))+
      facet_edges(~cond_1)+
      facet_nodes(~cond_1)+
      theme(strip.background = element_blank(),
            strip.text = element_text(size=7.5),
            legend.title = element_text(size = 10),
            panel.background = element_rect(fill = NA, color = "black"))
```
The resulting plot (reported below) is similar to what I expected but I miss some edges (in condition B, eg CD3->pSTAT4 and CD25->pS6)  . I do not know what I am doing wrong. Could someone please help me?
![Screenshot 2020-07-08 at 06 53 13](https://user-images.githubusercontent.com/68029518/86960365-50322300-c157-11ea-99a7-28f23f13b380.png)

**Comment by thomasp85** [comment]
There are two issues in your code: First, you cannot add two faceting functions to your plot, only the last one will have an effect. Second, the reason why you are not seeing the last lines is due to your network which has been encoded wrong. They are going between nodes in condition A and nodes in condition B and are thus not drawn
