### ISSUE TITLE
Problems with installation of ggraph

### ISSUE THREAD

**Issue by danieljimenez88m** [thomasp85/ggraph#255]
Hi Thomas, I'm having problems with the ggraph library.

When I run this code: 

bigram_frame %>%
  filter (n>=5) %>%
  visualize_bigrams()

I get the following error message:
Error in ggraph(., layout = "kk") : could not find function "ggraph"

Then I installed ggraph from the main source in github and I get:

Error: Failed to install 'ggraph' from GitHub:

Can you help me out? Thank you!

**Comment by thomasp85** [comment]
Hi. I would need some more information besides it just not working. Can you provide the full installation output along with the code you used?
