### ISSUE TITLE
use circular image node in graphs

### ISSUE THREAD

**Issue by SimonDeDeyne** [thomasp85/ggraph#257]
Any pointers on how to use raster images (jpg, png) within the circular nodes of a graph?
Mostly thinking of something along the linkes of [visNetwork](https://datastorm-open.github.io/visNetwork/image_icon.html).

Thank you

**Comment by thomasp85** [comment]
You may be able to use ggimage, but it would be untested

**Comment by mgei** [comment]
ggimage works see this: https://stackoverflow.com/a/65467968/9285732
