### ISSUE TITLE
Edge plotting memory usage with large networks

### ISSUE THREAD

**Issue by twelvespot** [thomasp85/ggraph#259]
Really appreciate the effort you've put into tidygraph and ggraph. My issue comes about when I built my company's data into a network, I took a small size (450k rows of connections) tidygraph worked fine but then I plotted with ggraph and then R ran out of memory. 

The actual issue is: Can multiple edges between the same nodes be dropped only when using geom_edge_link and the width set to the frequency of connections between those nodes? This way, ggraph won't plot 450k edges on top of each other but will retain the position of the nodes that is a result of node frequency in the data. For example, I plotted only "distinct" rows but this changes the network plot significantly since each connection is now assumed to be only a single occurrence, which may not put the most appropriate node in the center of the network.

**Comment by thomasp85** [comment]
The issues arises because the default edge type chops up edges in small segment to support showing gradients. Use `geom_edge_link0()` to get a less feature packed but more performant version

**Comment by thomasp85** [comment]
As for simplifying the graph so only one edge is drawn between them I'd suggest doing that in tidygraph, keeping a score of the number of edges originally in the data. This can then be used as an edge weight when calculating the layout

**Comment by twelvespot** [comment]
Thank you so much for clarifying! Will try those suggestions this weekend.

**Comment by twelvespot** [comment]
That has solved my problems! Thank you again.
