### ISSUE TITLE
Making the nodes bigger to fit the node texts (similar to the graphviz outputs)

### ISSUE THREAD

**Issue by gokceneraslan** [thomasp85/ggraph#261]
I wonder if it's possible to make plots like this one:

![](https://cloud.githubusercontent.com/assets/2606663/8525018/cad3a288-23fe-11e5-813c-bd205a47eed8.png)

where nodes with longer text are bigger. This is the output from graphviz, which has a cool feature to do this.

Another example:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1140359/96609270-542e1f00-12c8-11eb-904d-9fab385eb636.png">

**Comment by thomasp85** [comment]
This is not possible with all types of looks (yet). `geom_node_label()` allows you to place a books below the node text but the size of the box will not be used in any layout calculation and may thus overlap
