### ISSUE TITLE
tree layout is unstable and sometimes the nodes are perfectly overlapping

### ISSUE THREAD

**Issue by gokceneraslan** [thomasp85/ggraph#262]
I have this simple code producing the following plot:

```R
ggraph(graph, layout='tree') + 
    geom_edge_arc(aes(width=score), strength=0.1) + 
    geom_node_point(aes(fill=type), size=20., shape=21) + 
    geom_node_text(aes(label=node_id), color='white') + 
    scale_fill_brewer(type='qual', palette='Set1') +
    theme_graph(fg_text_colour = 'white')
```

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1140359/97122322-77f3c980-16fb-11eb-961a-7b086b914a62.png">

where some nodes are perfectly overlapping, which I guess shouldn't happen.

When I run it again, sometimes I get something even worse:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/1140359/97122445-3f082480-16fc-11eb-9192-99a7c4262a45.png">

It is ok that the layout algorithm is not deterministic, but I don't understand why it leads to such bad layouts.

Here is what happens with layout_nicely:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/1140359/97122489-90181880-16fc-11eb-90d2-25080d164167.png">

**Comment by thomasp85** [comment]
This should be filed in igraph since the layout comes from there
