### ISSUE TITLE
Changing package default font?

### ISSUE THREAD

**Issue by mbojan** [thomasp85/ggraph#265]
I ran into #67 again, and so did my inexpeRienced students...

Perhaps following https://github.com/thomasp85/lime/issues/14#issuecomment-328827703 this should not be a default after all? 

Don't we want a bullet-proof default that works everywhere and produces figures similar to other ggplot2 figures (with defaults)? Anybody after superior information density can install `extrafont`, as suggested here https://github.com/thomasp85/ggraph/issues/67#issuecomment-430399233, and thicken their information density to their leisure...

Please reconsider @thomasp85 .

**Comment by thomasp85** [comment]
the default (no additional theme) is equivalent to the look of ggplot2 - just don't add `theme_graph()`

**Comment by mbojan** [comment]
OK. I tried to get the white background set otherwise by `theme_graph()`. This does not work, am I missing something?

```r
library(ggraph)
library(tidygraph)
data("highschool", package="ggraph")
highschool %>%
  as_tbl_graph(highschool) %>%
  ggraph() +
  geom_edge_link() +
  geom_node_point() +
  theme(
    plot.background = element_rect(fill="white", colour = "white")
  )
```

**Comment by thomasp85** [comment]
This seems to work fine?

``` r
library(ggraph)
#> Loading required package: ggplot2
ggraph(highschool) +
  geom_edge_link() +
  geom_node_point() +
  theme(
    plot.background = element_rect(fill="white", colour = "white")
  )
#> Using `stress` as default layout
```

![](https://i.imgur.com/L8EMcMW.png)

<sup>Created on 2020-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
You need to set the `panel.background` theme element
