### ISSUE TITLE
Suggestion: Force-Directed Edge Bundling

### ISSUE THREAD

**Issue by psimm** [thomasp85/ggraph#267]
A new geom_edge_force that uses force-directed edge bundling would let users create much better "hairball" visualizations that are easier to read.  In contrast to geom_conn_bundle it would not require connections, which would make it applicable to many more networks.

Reference:
Holten, Danny, and Jarke J. Van Wijk. "Force‐Directed Edge Bundling for Graph Visualization." Computer Graphics Forum (Blackwell Publishing Ltd) 28, no. 3 (2009): 983-990.

An example in d3: <https://github.com/upphiminn/d3.ForceBundle>

Unfortunately performance seems to be a major concern.

**Comment by thomasp85** [comment]
Thanks. I've had my eye on that for a while but implementation is non-trivial. It will have to wait for a time with a lot of free time

**Comment by schochastics** [comment]
I have been working on this and i think I am pretty close (neglecting potential style guide errors)

This is the stat I wrote:
```r
StatEdgeForceBundle <- ggproto('StatEdgeForceBundle', StatIdentity, setup_data = function(data, params) {
    if (any(names(data) == 'filter')) {
      if (!is.logical(data$filter)) {
        stop('filter must be logical')
      }
      data <- data[data$filter, names(data) != 'filter']
    }
    data <- remove_loop(data)
    force_bundle(data,params)

  },
  required_aes = c('x', 'y'),
  default_aes = aes(filter = TRUE),
  extra_params = c('K','C','P','S','P_rate','I','I_rate','compatibility_threshold','eps')
)
```
the extra parameter are needed for the force bundling.
And here is the geom
```r
geom_edge_forcebundle0 <- function(mapping = NULL, data = get_edges(),
                                   position = 'identity', arrow = NULL,
                                   lineend = 'butt', show.legend = NA,
                                   K = 1, C = 6, P = 1, S = 0.04, P_rate = 2,
                                   I = 50, I_rate = 2/3, compatibility_threshold = 0.1,
                                   eps = 1e-8, ...) {
  mapping <- complete_edge_aes(mapping)
  mapping <- aes_intersect(mapping, aes(x = x, y = y,
                                        xend = xend, yend = yend))
  layer(
    data = data, mapping = mapping, stat = StatEdgeForceBundle,
    geom = GeomEdgePath, position = position,
    show.legend = show.legend, inherit.aes = FALSE,
    params = expand_edge_aes(
      list(
        arrow = arrow, lineend = lineend, na.rm = FALSE, 
        K = K, C = C, P = P, S = S, P_rate = P_rate, I = I, I_rate = I_rate, 
        compatibility_threshold = compatibility_threshold, eps = eps,
        interpolate = FALSE, ...
      )
    )
  )
}
```

It (surprisingly to me!) works, but I get the warning
```
Warning: Ignoring unknown aesthetics: xend, yend
```

Which I am unsure where it comes from. 
Any pointers? 
Also, is the way I designed the Stat part ok? 

I am also wondering if a geom_edge_forcebundle() geom_edge_forcebundle2() make sense since the force bundling always needs intermediate points.

**Comment by thomasp85** [comment]
@schochastics do you want to add this?

**Comment by schochastics** [comment]
@thomasp85 what is your release schedule? I have a second algorithm that I would also implement. I am going on parental leave tomorrow though, so making a proper PR would take a while. From my side it is no problem to postpone it to the next release.

**Comment by thomasp85** [comment]
one way around it is to use memoisation - I think I at least would like to give it a try

**Comment by schochastics** [comment]
That is actually a great idea!

**Comment by schochastics** [comment]
Yup, can confirm that [memoise works](https://github.com/schochastics/ggraph/blob/edge_bundle/R/geom_edge_force_bundle.R#L155).
