### ISSUE TITLE
Possible to control line style for edges?

### ISSUE THREAD

**Issue by beroe** [thomasp85/ggraph#27]
In addition to having arrowheads at the end of a line segment, it would be great to be able to put the directionality along the length of the stroke, as in the attached examples. Is there a way that could be implemented in the network graphs?

![screen shot 2017-01-18 at 14 27 42](https://cloud.githubusercontent.com/assets/871533/22085796/780c2b00-dd8a-11e6-8322-faa489befd2a.png)

**Comment by thomasp85** [comment]
No. Unfortunately this comes downs to restrictions in the underlying grid package... Would be cool though:-)
