### ISSUE TITLE
Coloring Conn Bundle by Node Group

### ISSUE THREAD

**Issue by willi3by** [thomasp85/ggraph#272]
Hi,

I am trying to create a hierarchical edge bundling plot where the connections are colored by the node group from which they originate. So far I have achieved the following, where the connections are colored by continuous connection weights and nodes colored by group.

![edge_bundling](https://user-images.githubusercontent.com/42728698/102129139-e3fdce80-3e1c-11eb-9eb8-1a7b7a962543.png)

And here is the code used to generate the plot:
```
p <- ggraph(mygraph, layout="dendrogram", circular=T) + 
  geom_node_point(aes(filter=leaf, color=group), size=3) +
  geom_conn_bundle2(data = get_con(from = from, to = to, col=col), aes(col=col, alpha=col)) +
  scale_edge_color_distiller('', direction = 1, guide = 'edge_colorbar') + 
  coord_fixed() + 
  theme_classic() +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
      panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),plot.background=element_blank())
```
where col is a numeric vector of values between -1 and 1. I created a numeric vector of the same length with discrete values indicating originating node group for each connection but when I try to add it in place of col, I get the error:

```
Error: Aesthetics must be either length 1 or the same as the data (725): edge_colour
Run `rlang::last_error()` to see where the error occurred.
```
Is there a way to achieve what I am trying to do? 

My end goal is actually to color the edges by a gradient specific to the nodes which it connects, but I thought a solid color based on one node is a good place to start. 

Thanks for your time and I really appreciate the package! It fills a much needed gap not available elsewhere that I am aware of.

**Comment by thomasp85** [comment]
This was surprisingly harder than I expected coming into this question so thank you for posing it.

The issue is that some layouts reorder the nodes - this is especially true for hierarchical layouts since some of these expect e.g. leafs to be plotted last so as to not be occluded by parent nodes.

On the dev version, `...` now accepts tidy evaluation on the node data in the original order so (based on the `geom_conn_bundle()` example in the docs) you can do this:

``` r
ggraph(flareGraph, 'dendrogram', circular = TRUE) +
    geom_conn_bundle(aes(colour = group),
                     data = get_con(importFrom, importTo, group = class[importFrom]),
                     edge_alpha = 0.25
    ) +
    geom_node_point(aes(filter = leaf, colour = class)) +
    coord_fixed()
```

![](https://i.imgur.com/g0DZbpu.png)
