### ISSUE TITLE
More examples on the data parameter of geom_* functions

### ISSUE THREAD

**Issue by gokceneraslan** [thomasp85/ggraph#274]
Hi,

I would like to use different values of nudge_x/nudge_y parameters in `geom_edge_label()` for different sets of nodes. I thought I can subset the graph and call geom_edge_label for each subgraph with different `data=subgraph` parameters but apparently this is not the right way, because I get `Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class tbl_graph/igraph` error.

I was wondering if there are some examples about how to properly use the data argument of geom_node* and geom_edge* dunctions.

Cheers.

**Comment by thomasp85** [comment]
I think the most straightforward way is to use the `filter` aesthetic to only show the geom for the edges you want

**Comment by gokceneraslan** [comment]
Sorry, I meant `geom_node_text` and `geom_node_label` actually. There is no filter aesthetic for them, right?

**Comment by thomasp85** [comment]
There are filter aesthetics for all geoms

**Comment by gokceneraslan** [comment]
Oh ok, sorry again. I just didn't see it in the code: https://github.com/thomasp85/ggraph/blob/master/R/geom_node_text.R#L6
