### ISSUE TITLE
Nodes extend beyond edges of figure

### ISSUE THREAD

**Issue by jdfoote** [thomasp85/ggraph#280]
The following code produces a figure where portions of the nodes are at the edge of the figure. Are there different settings I should use to avoid this?

```
theme_set(theme_minimal())
df = data.frame(from = c("A","B"), to = c("B","C"))
colors = data.frame(name=c("A","B","C"), color = c("gold", "black", "black"))

G = graph_from_data_frame(d = df, vertices = colors)

plot = G %>%
  ggraph(layout = 'circle') +
  geom_node_point(aes(color = color), size = 15) + 
  geom_node_label(aes(label = name)) +
  #geom_edge_fan(width = .1) + 
  scale_color_manual(values = c("gold"='gold',"black"='black'), guide = F)
plot
```

![image](https://user-images.githubusercontent.com/452218/106181313-73f89d00-616b-11eb-99fd-8e0872e56f91.png)

**Comment by birdMig** [comment]
Hi,

Answer to that is in "layouts" tab of the ggraph vignette - you just need to set the margins of the graph:

`
set_graph_style(plot_margin = margin(1,1,1,1))
`
see here:  https://ggraph.data-imaginist.com/articles/Layouts.html

or you could add this line of code to avoid margins from clipping the nodes:

`coord_cartesian(clip = "off")`

good luck!

**Comment by jdfoote** [comment]
Thanks very much!

The `set_graph_style` command did not work for me, but `coord_cartesian` did.
