### ISSUE TITLE
R crashes when plotting one particular small dense graph with "stress" layout

### ISSUE THREAD

**Issue by simonheb** [thomasp85/ggraph#286]
I plot ~1000 varying graph structures in my data. It works for 999 but crashes on a single particular network. If I leave this one out, or use something else than "stress" it works. I can reproduce the issue with the attached file and this line of code:
```
g<-readRDS("weird-graph.RDS")
plot(g)  #this works
ggraph(g) #this doesn't
```
I don't get an error message, R simply crashes
![grafik](https://user-images.githubusercontent.com/4234597/111624852-7c289c80-87ec-11eb-8af8-f0cb835196aa.png)

[weird-graph.zip](https://github.com/thomasp85/ggraph/files/6163950/weird-graph.zip)

**Comment by schochastics** [comment]
This is not an issue of ggraph but [graphlayouts](https://github.com/schochastics/graphlayouts). I cannot reproduce the error with the weird graph. Can you check the code below?
```
g <- readRDS("weird-graph.RDS")
ggraph(g,"stress") +
  geom_edge_link()+
  geom_node_point()

```
