### ISSUE TITLE
Getting Started/Layouts Abound/Node-Edge Diagram Layouts/ Not reproducing properly

### ISSUE THREAD

**Issue by regiso** [thomasp85/ggraph#287]
Hi Thomas - I am falling in love with ggraph as I prepare an online class for graduate students in data vis. I am working in RStudio Server 4.0.3.  My students will need to work through the imaginist tutorial on their own and then create their own network graphs.

During my prep I ran into a puzzle in the imaginist tutorial  Layouts Abound section Node-Edge Diagram. The first chunk of code is not reproducing properly.  I copied the code exactly - the result prints only the first chart in the series AND the caption does not match. There is no problem however, in RSTudio 4.0.4 on my laptop. 

I suspect therefore this is a RStudio versioning issue and my students most likely will be constrained to 4.0.3.  Hopefully there will be an RStudio update before the class launches. In the meantime, can you please confirm that this is a versioning issue and that I should talk the students past this puzzle. 

Attached is an image of the graph outpout.
![plot](https://user-images.githubusercontent.com/16366682/112175513-aeac0e00-8bcd-11eb-95e9-da923133f2b0.png)

**Comment by thomasp85** [comment]
Hi - can you point me to exactly which chunk of code you are referring to?

**Comment by regiso** [comment]
Hi Thomas - 
Thanks for your reply. 
I'm not sure how it happened, but today all the code works perfectly and matches https://ggraph.data-imaginist.com/articles/Layouts.html!
Really, I did test it many times last week. 
My apologies for troubling you in the meantime.

FYI here is the chunk that was misbehaving last week....


`graph <- as_tbl_graph(highschool) %>% 
  mutate(degree = centrality_degree())

lapply(c('stress', 'fr', 'lgl', 'graphopt'), function(layout) {
  ggraph(graph, layout = layout) + 
    geom_edge_link(aes(colour = factor(year)), show.legend = FALSE) +
    geom_node_point() + 
    labs(caption = paste0('Layout: ', layout))
})
`
