### ISSUE TITLE
Scale color gradient for nodes

### ISSUE THREAD

**Issue by mgree013** [thomasp85/ggraph#294]
I am attempting to scale the colour/color gradient of geom_node_points in ggraph but don't see any options in the ggraph package. The nodes are a continuous color gradient of the response variable and Im trying to set a limit on the colour gradient from 0 to 1, but when i set the limit all the nodes return as the same colour.

I've tried some workarounds from ggplot to no avail such as scale_color_gradientn and scale_color_viridis. Is there a way to do this? I'm happy to provide an example if that would be helpful

**Comment by schochastics** [comment]
@mgree013 still an issue? if so, happy to take a look if you provide an example
