### ISSUE TITLE
question: geom_edge_loop absolute loop size

### ISSUE THREAD

**Issue by langenberg** [thomasp85/ggraph#304]
Hi everyone!

Thanks for your work on this great package!

I was wondering if it is possible to set an absolute size for a loop using the geom_edge_loop function? When I resize the viewer, the loop gets resized too. I would like to have a constant loop size though. I played around with the strength aesthetic but I didn't get the result that I hoped for. Is it possible to set the unit for geom_edge_loop to e.g. "mm"?

Thanks for your help!

Cheers,
Benny

**Comment by thomasp85** [comment]
That is not possible at the moment and I'm not sure it will be added unless someone provides a PR
