### ISSUE TITLE
circle packing is disordered, when data has a larger hierarchy.

### ISSUE THREAD

**Issue by Mpaperlee** [thomasp85/ggraph#305]
I have use ggraph and ggsubplot create circle packing plots with my phylogenetic data. It works great when my phylogenetic tree is small. However, it doesn't work when my tree is larger.
when my tree is small
![image](https://user-images.githubusercontent.com/22189984/155984717-8d8a24fb-3f69-48e0-8b3b-406898dbdab9.png)
when larger
![image](https://user-images.githubusercontent.com/22189984/155984846-d7f59412-eb12-4e52-af85-c41d08fcfb45.png)

the Circles in lower hierarchies are too big.

please could you tell me how to fix it
thanks

**Comment by JGippet** [comment]
Hi @thomasp85,
I have the same problem with ggraph.
This issue has also been reported 2 ya on stackoverflow (https://stackoverflow.com/questions/65151687/circle-packing-with-ggraph-circles-in-lower-hierarchies-are-too-big).

I tried to find a way around it but I couldn't... please help!!! 

All the best
