### ISSUE TITLE
use geom_node_text add label   Encountered a problem

### ISSUE THREAD

**Issue by nolanjj** [thomasp85/ggraph#330]
![image](https://user-images.githubusercontent.com/35267241/192746262-1e16b3bf-9bdf-4b5d-81ef-6f493bc13bc0.png)

I follow the tutorials on this websit
https://r-graph-gallery.com/311-add-labels-to-hierarchical-edge-bundling.html
copied the drawing code

But the picture is different

in my pictire  point subgroup_1 on the bottom right  not  on top
why

**Comment by nolanjj** [comment]
help！！！

**Comment by thomasp85** [comment]
it's hard to say - when I run the code you linked to I get the same result as the link, not yours...

Maybe ensure you have the latest version of R and the latest versions of all packages, restart, and try again

**Comment by nolanjj** [comment]
> it's hard to say - when I run the code you linked to I get the same result as the link, not yours...
> 
> Maybe ensure you have the latest version of R and the latest versions of all packages, restart, and try again

thanks!!!,I will try again
