### ISSUE TITLE
Error in try_fetch(utils::getFromNamespace(algorithm, "igraph"), error = function(cnd) { : could not find function "try_fetch

### ISSUE THREAD

**Issue by MANZHAOHUI** [thomasp85/ggraph#337]
when I was using clustree, I constantly got this error despite my reinstalling ggraph.
cluster_tree <- clustree(combined.int.clustree,prefix = "integrated_snn_res.") combined.int.clustree is a seurat single cell RNA object.

**Comment by schochastics** [comment]
Can you provide a code snippet that reproduces this error?

**Comment by thomasp85** [comment]
Also, I assume this is a clustree issue, not a ggraph issue

Closing but feel free to reopen with a reprex
