### ISSUE TITLE
ggraph unable to collate and parse R files for package ‘ggraph’

### ISSUE THREAD

**Issue by Corina-Mihaela-Motofeanu** [thomasp85/ggraph#365]
Hey, I am trying to install ggraph for clusterProfiler but came across this issue:

installing to /home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-ggraph/00new/ggraph/libs
** R
Error in parse(outFile) : 
  /tmp/Rtmp5JbfQ3/R.INSTALL3afc51d14a28/ggraph/R/edges.R:208:21: unexpected '>'
207:     edges$.id <- id
208:     edges <- edges |>
                         ^
ERROR: unable to collate and parse R files for package ‘ggraph’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/ggraph’

The downloaded source packages are in
	‘/tmp/RtmpPPHGBN/downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘ggraph’ had non-zero exit status

Anyone knows what is wrong?

**Comment by bockthom** [comment]
We are in the same boat: I already encountered and reported this issue last Thursday, see issue #364. The developers of ggraph inadvertently used the native pipe in their new release, which is a language feature of R that was introduced in R 4.1. Thus, the current version of ggraph (which was released one week ago) does not compile with R versions prior to R 4.1, such as yours (you used 4.0).

In [this comment](https://github.com/thomasp85/ggraph/issues/364#issuecomment-1970639704), the maintainer of ggraph acknowledged that a patch release for ggraph is necessary to fix that. They are currently discussing on whether to adjust the R-version dependency or to revert the use of the inadvertently used language feature. As there have already been others who voted for reverting the change, I hope that they will revert it and fix this problem soon, but I am still waiting for a response of the maintainer in issue #364. Hopefully, they can fix this soon...

I hope that helps you on the long run. For a fast work-around, I (as a user of ggraph, not a contributor) suggest to either to upgrade to a more recent R version (if possible on the machine you use) or install a previous version ggraph (which might also not be the desired solution as you might miss current fixes in older package versions).
