### ISSUE TITLE
Arrowheads overlap with/vanish under nodes

### ISSUE THREAD

**Issue by slockton** [thomasp85/ggraph#39]
The lines representing edges always meet - they never end at the outside of a node. This has the side-effect of arrow heads either overcrowding a node, or vanishing under a node, depending on the order of geoms in your code.

Is there a way that the edge lines could terminate at the outside perimeter of a node so that arrows point to nodes rather than getting swallowed up?

**Comment by thomasp85** [comment]
Use the recently added `start_cap` and `end_cap` arguments for `geom_edge_*()`, or encode direction using a colour, alpha, and/or width gradient to avoid cluttered arrowheads
