### ISSUE TITLE
D3 force layout

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/ggraph#48]

**Comment by cjyetman** [comment]
I have some experience with this (plotting network graphs with d3-force from an r-pkg) as a collaborator on the [networkD3 package](https://github.com/christophergandrud/networkD3). I'd be happy to discuss what your strategy is for this here, and contribute if I can.

**Comment by thomasp85** [comment]
Thanks... The strategy is pretty straightforward (at least on paper) — port the algorithm to C++ as with the other layout algorithms... How much work this is going to be is still unknown, but I have a pretty good grasp if Mikes coding style so I don't expect too much trouble

**Comment by cjyetman** [comment]
so, the goal is to replicate in ggplot a static version of the the end result of *n* iterations of d3-force's many-body algorithm?

**Comment by thomasp85** [comment]
Jep

**Comment by thomasp85** [comment]
Implemented in `particles`
