### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by wlongabaugh** [thomasp85/ggraph#60]
Hi! I saw your new posting over on data-imaginist, and your request for network visualization suggestions.

How about adding the ability to visualize networks using the BioFabric technique? I.e. see: https://github.com/wjrl/RBioFabric

Thanks!

**Comment by thomasp85** [comment]
Thanks. Already on my mind as per #47. Closing as this is duplicate

**Comment by wlongabaugh** [comment]
Whoops! My apologies. Should have looked at the list more closely. Thanks.

**Comment by thomasp85** [comment]
No worries
