### ISSUE TITLE
ggraph won't install

### ISSUE THREAD

**Issue by JB70** [thomasp85/ggraph#61]
Used RStudio Version 1.0.44 to install ggraph from CRAN. Dependencies were installed without a problem but ggraph not. Error message: 
"Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘ggraph’
  These will not be installed"

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by domiden** [comment]
You need to install a set of development tools providing the named programming languages and infrastructure. I don't have experiences of installing those tools on Windows systems. So, you need to read the following instructions/websites:

- [R for Windows FAQ: Can I install packages into libraries in this version?](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Can-I-install-packages-into-libraries-in-this-version_003f)
- [Building R for Windows](https://cran.r-project.org/bin/windows/Rtools/)
- [Install Rtools for Windows](https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows)

Hopefully, this comment was helpful in one way or another.  :dart:
