### ISSUE TITLE
Option to highlight certain nodes?

### ISSUE THREAD

**Issue by seth-1** [thomasp85/ggraph#63]
Thank you for the great package!

Is it possible to highlight certain groups in the ggraph plot? Is there something similar to igraphs mark.groups argument in ggraph?

```r
library(igraph)
g = make_graph("Frucht")
l = layout.reingold.tilford(g,1)
plot(g, layout=l, mark.groups = c(1,3,6,12,5), mark.shape=1)
```
![forpost](https://cloud.githubusercontent.com/assets/10029760/23401268/617bfb9e-fda7-11e6-97ed-bc733a31591a.png)

**Comment by thomasp85** [comment]
this will be provided through `ggforce::geom_mark_*` - no need for anything to be done in ggraph

**Comment by seth-1** [comment]
Thank you for remembering! I will have a look at it.

**Comment by simonheb** [comment]
Are there any news on this?
