### ISSUE TITLE
Problem with Arial Narrow font

### ISSUE THREAD

**Issue by mbojan** [thomasp85/ggraph#67]
I am using `ggraph` in RMarkdown document with `dev="svg"`:

```
ggraph(g, layout="kk") +
  geom_edge_link() +
  geom_node_point(aes(shape=Płeć, fill=leftright, stroke=ego), size=8) +
  scale_shape_manual(breaks=c("Mężczyzna", "Kobieta"), values=c(21, 22)) +
  scale_fill_gradient(low="red", high="blue", name="Lewica-Prawica") +
  geom_node_label(aes(label=name), repel=TRUE)  +
  theme_graph()

## Warning in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
## font family 'Arial Narrow' not found in PostScript font database
```

Looks like the `theme_graph()` is to blame.

PS. The gradient legend also dissappears, but this seems to be a `ggplot2` problem.

**Comment by mbojan** [comment]
So far I go away with `theme_graph(base_family="sans")`.

**Comment by methodds** [comment]
I experience the same problem on a Windows system:
```
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
```

**Comment by thomasp85** [comment]
Simply provide a different @mbojan - Arial Narrow is present in almost every system and provide superior information density, hence its choice as default

**Comment by jacob-long** [comment]
I don't know much at all about how grid searches for fonts, but I've had two systems (one macOS, one Windows 10) that definitely had Arial Narrow installed but still generated these warnings (which become errors when knitting to PDF, though I'm not certain whether that's more of a LaTeX issue).

**Comment by cschwem2er** [comment]
fyi, this problem also occurs when using the [hrbrthemes](https://github.com/hrbrmstr/hrbrthemes) package.

**Comment by malcolmbarrett** [comment]
Try adding `extrafont::loadfonts()` to your markdown file. You may need to do `extrafont::font_import()` and restart your session first.

**Comment by GildasLepennetier** [comment]
> Try adding `extrafont::loadfonts()` to your markdown file. You may need to do `extrafont::font_import()` and restart your session first.

This is amazing, how is it possible that I missed that? Thanks @malcolmbarrett

**Comment by mbojan** [comment]
I ran into this again, and so did my inexpeRienced students...

Perhaps following https://github.com/thomasp85/lime/issues/14#issuecomment-328827703 this should not be a default after all? 

I want a bullet-proof default that works everywhere and produces figures similar to other ggplot2 figures (with defaults). Anybody after superior information density can install `extrafont`, as @malcolmbarrett suggested, and thicken their information density to their leisure...

Please reconsider @thomasp85 .

**Comment by Drawing12** [comment]
you can download from here, i have downloaded working fine: https://dafont.style/download/arial-narrow-font.html
