### ISSUE TITLE
"promise already under evaluation" with geom_node_text(..., repel = TRUE)

### ISSUE THREAD

**Issue by petehobo** [thomasp85/ggraph#69]
Hi,

I've hit a problem when calling `geom_node_text()` with the `repel = TRUE` parameter.  See https://github.com/dgrtwo/tidy-text-mining/issues/27 for more detail, but in summary:

```
data_frame(node1 = 1:4, node2 = 2:5) %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link() +
    geom_node_point() +
    geom_node_text(aes(label = name), repel = TRUE)
```

throws

> Error in data.frame(x = xlim, y = ylim) : 
>   promise already under evaluation: recursive default argument reference or earlier problems?
> 

By comparison, replacing `repel = TRUE` with `vjust = 1, hjust = 1`:

```
data_frame(node1 = 1:4, node2 = 2:5) %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link() +
    geom_node_point() +
    geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```

 (as suggested in the above link) runs fine.

Apologies if the source of the error is a different package; happy to raise it elsewhere if need be.

**Comment by thomasp85** [comment]
Fixed in ggrepel issue 72
