### ISSUE TITLE
Extra edges drawn when using label_rect() with tree layout

### ISSUE THREAD

**Issue by NathanCDay** [thomasp85/ggraph#70]
I can only create this problem when using `layout = "tree"` and `start_cap = label_rect()`. Any other start/end cap geoms work fine and any other layout works fine too. But when both conditions are met, extra edges are drawn from a (random?) subset of nodes to the bottom left corner (-1,0) of the plot. 

```{r}
library(igraph)
library(ggraph)

#small data
simple <- make_graph('bull')
V(simple)$name <- c('Thomas', 'Bob', 'Hadley', 'Winston', 'Baptiste')
E(simple)$type <- sample(c('friend', 'foe'), 5, TRUE)

# bad graph with the phantom extra edges
ggraph(simple, layout = 'tree') + 
    geom_edge_link(aes(start_cap = label_rect(node1.name),
                       end_cap = label_rect(node2.name)), 
                   arrow = arrow(length = unit(4, 'mm'))) + 
    geom_node_text(aes(label = name))
```
![image](https://cloud.githubusercontent.com/assets/808225/25236352/a1e8fb24-25b5-11e7-9192-c658f98f4445.png)

**Comment by rexdouglass** [comment]
I'm getting the same problem with any layout. I'm showing two behaviors (1) Some edges don't get drawn at all. (2) Some edges get drawn to the bottom left corner. Resizing the plot window by hand through the operating system will sometimes shift which edges demonstrate the problem. That suggests it's something to do with the automatic layout code, giving it a little more room can sometimes solve it.

p <- ggraph(g1, layout = 'auto') + 
  geom_edge_link(aes(start_cap = label_rect(node1.name),
                     end_cap = label_rect(node2.name)), 
                 arrow = arrow(length = unit(1, 'mm'))) + 
  geom_node_text(aes(label = name), size=2)
p
