### ISSUE TITLE
Modifying the dataframe in between creating the layout and plotting

### ISSUE THREAD

**Issue by brianwdavis** [thomasp85/ggraph#71]
A minimal example of what I'd like to do is plot a tree, and then draw a rectangle under each branch of a tree to highlight some particular structure.

Here's some code attempting that:
```
iris[,1:4] %>% 
  dist() %>% 
  hclust() %>% 
  as.dendrogram() %>% 
  create_layout(., layout = "dendrogram") %>% 
  ggraph() + geom_edge_link() + 
  geom_node_text(aes(label = ggraph.index)) +
  geom_node_tile(aes(width = 20, 
                     height = y, 
                     y = y/2, 
                     fill = factor(ggraph.index), 
                     filter = ggraph.index %in% c(143,298)),
                 alpha= 0.5, colour = NA)
```

![image](https://cloud.githubusercontent.com/assets/13338560/25406531/014fc6b0-29d5-11e7-953c-815d303d6fe0.png)

I hard-coded in the `ggraph.index` value because I couldn't see any other way to identify those nodes, but that's not an insurmountable problem. Really the issue is that I'd like to do something like:

```
iris[,1:4] %>% 
  dist() %>% 
  hclust() %>% 
  as.dendrogram() %>% 
  create_layout(., layout = "dendrogram") %>% 
  mutate(fac = cut(ggraph.index, c(0,143,298))) %>%    # define groups
  group_by(fac) %>%                                    # group by clusters
  mutate(groupxmin = min(x), groupxmax = max(x)) %>%   # find extents of all leaves within each group
  ggraph() + 
  geom_edge_link() + 
  geom_node_tile(aes(width = groupxmax-groupxmin,      # plot width to correct extents
                     height = y,
                     x = (groupxmax+groupxmin)/2,      # center on the extents
                     y = y/2,
                     fill = fac,
                     filter = ggraph.index %in% c(143,298)),
                 alpha= 0.5, colour = NA)

```

The first part of this code (prior to the `ggraph()` call) generates exactly the dataframe I'd like:

```
Source: local data frame [299 x 10]
Groups: fac [3]

       x         y  leaf  label members circular ggraph.index     fac groupxmin groupxmax
   <dbl>     <dbl> <lgl> <fctr>   <int>    <lgl>        <int>  <fctr>     <dbl>     <dbl>
1  0.000 0.0000000  TRUE    108       1    FALSE            1 (0,143]         0        71
2  1.000 0.0000000  TRUE    131       1    FALSE            2 (0,143]         0        71
3  0.500 0.2645751 FALSE              2    FALSE            3 (0,143]         0        71
4  2.000 0.0000000  TRUE    103       1    FALSE            4 (0,143]         0        71
5  3.000 0.0000000  TRUE    126       1    FALSE            5 (0,143]         0        71
6  4.000 0.0000000  TRUE    130       1    FALSE            6 (0,143]         0        71
7  3.500 0.3464102 FALSE              2    FALSE            7 (0,143]         0        71
8  2.750 0.5196152 FALSE              3    FALSE            8 (0,143]         0        71
9  1.625 0.5567764 FALSE              5    FALSE            9 (0,143]         0        71
10 5.000 0.0000000  TRUE    119       1    FALSE           10 (0,143]         0        71
# ... with 289 more rows
```

But attempting to run the whole chunk, of course, throws the error: 
```
Error in create_layout.default(graph, layout, ...) : 
  No layout function defined for objects of class grouped_dftbl_dftbldata.frame
```

A work-around I tried was replacing `ggraph()` with a call to `ggplot()` and using the standard form of `geom_tile`, but then `geom_edge_link` doesn't work, and the `filter = ` aesthetic doesn't work either.

My best result so far is not ideal, because it requires modifying the data inside the `geom` call, which can be cumbersome in other situations.

```
temp.iris <- iris[,1:4] %>% 
  dist() %>% 
  hclust() %>% 
  as.dendrogram() %>% 
  create_layout(., layout = "dendrogram") 


temp.iris %>% 
  ggraph() + 
  geom_edge_link() +
  geom_node_tile(data = temp.iris %>% 
                   mutate(fac = cut(ggraph.index, c(0,143,298))) %>% 
                   group_by(fac) %>% 
                   mutate(groupxmin = min(x), groupxmax = max(x)),
            aes(width = groupxmax-groupxmin,
                     height = y,
                     x = (groupxmax+groupxmin)/2,
                     y = y/2,
                     fill = fac,
                     filter = ggraph.index %in% c(143,298)),
                 alpha= 0.5, colour = NA)
```

![image](https://cloud.githubusercontent.com/assets/13338560/25406549/0bc78678-29d5-11e7-92da-0b8523305a80.png)

**Comment by thomasp85** [comment]
I'm working on a generalised solution for marking up nodes that would solve this problem. The timeframe is unknown though, so it doesn't really help you much right know.

Is this a one-of that you have solved with your hack (but want to learn a better approach), or do you need a stable solution *right know* for making multiple plots of the same type?

**Comment by brianwdavis** [comment]
This one-off hack is just a demonstration of what I want: a way to manipulate the data fed into the `geom`s the same way I would with `dplyr` and `ggplot`. Is there any way to use `dplyr` verbs on the dataframe generated by `create_layout` while preserving the other classes of that object? This isn't an urgent need, but it seems like it would be important within the general split-apply-combine philosophy of the tidyverse.

**Comment by thomasp85** [comment]
This could be done by passing a function to the `data` argument in the geom... This is also how all edge geoms recieve different data
