### ISSUE TITLE
can't convert dendrogram object to igraph object then plot as dendrogram with geom_edge_elbow

### ISSUE THREAD

**Issue by wkc1986** [thomasp85/ggraph#72]
Trying to plot an igraph object that was converted from a dendrogram object with `den_to_igraph`, with dendrogram layout and `geom_edge_elbow` gives an error. MWE:

```
library(ggraph)
library(igraph)

dendro <- as.dendrogram(hclust(dist(iris[-5])))
igraf <- den_to_igraph(dendro)
ggraph(igraf, "dendrogram") + geom_edge_elbow()
```

gets

`Error in eval(expr, envir, enclos) : object 'direction' not found`

I would plot the dendrogram object directly, but I want to use `tree_apply`, which, as I understand, currently only works on igraph objects.

**Comment by thomasp85** [comment]
Fixed in 36fc2a9
