### ISSUE TITLE
Some scale_edge_* only work when ggraph is loaded

### ISSUE THREAD

**Issue by Ax3man** [thomasp85/ggraph#75]
It appears some scales only work when ggraph is actually loaded. When referring to them with `::` the correct guide cannot be found. When the guide is manually specified, the scale does work (with a warning), but no guide is shown.

```
data('highschool', package = 'ggraph')
graph <- igraph::graph_from_data_frame(highschool)

ggraph::ggraph(graph, layout = 'kk') + 
  ggraph::geom_edge_link(ggplot2::aes(color = year)) + 
  ggraph::scale_edge_color_gradient()
# Error in get(as.character(FUN), mode = "function", envir = envir) : 
#   object 'guide_edge_colourbar' of mode 'function' was not found

ggraph::ggraph(graph, layout = 'kk') + 
  ggraph::geom_edge_link(ggplot2::aes(color = year)) + 
  ggraph::scale_edge_color_gradient(guide = ggraph::guide_edge_colorbar())
# Warning message:
#   In guide_train.colorbar(guide, scale) :
#   colorbar guide needs colour or fill scales.
```

These examples do work after `library(ggraph)`.

I believe this will be a problem for code in packages, as `requireNamespace` does not appear to alleviate the problem.

**Comment by thomasp85** [comment]
This is an unfortunate result of how scale extensions are made in ggplot2 and outside the reach of ggraph or any other extension package. The solution is to import and reexport the needed function in your own package...

**Comment by Ax3man** [comment]
Ok, that solution is fine. Do you mean `guide_edge_colorbar`?

**Comment by thomasp85** [comment]
Thanks @Ax3man

**Comment by llrs** [comment]
I don't know if it is the way I use packages, but I thought I couldn't modify the color gradient of edges because I didn't see anything in their vignette. Thank for mentioning this here (as well as on #25) !
