### ISSUE TITLE
Clipping issue

### ISSUE THREAD

**Issue by mailund** [thomasp85/ggraph#77]
I don't know if this is a problem with gridExtra::grid.arrange or ggraph, but there is an issue with parts of graphs being clipped.

Consider the code:

```r
devtools::install_github("mailund/ralgo")
library(ralgo)

plots <- vector("list", 4)
tree <- empty_search_tree()
for (i in 1:4) {
  tree <- insert(tree, i)
  plots[[i]] <- plot(tree)
}
```

Here I construct four search tree plots and save them in a list. If I print one of them I get a plot where all of the graph is visible.

```r
plots[[3]]
```
<img width="496" alt="screen shot 2017-07-13 at 08 08 28" src="https://user-images.githubusercontent.com/3206538/28152856-e2db441e-67a2-11e7-923c-fa1a6f8c32e9.png">

If I want to add all four plots in a grid, however, the top of the graphs get clipped

```r
gridExtra::grid.arrange(plots[[1]], plots[[2]],
                        plots[[3]], plots[[4]],
                        nrow = 2)
```

<img width="507" alt="screen shot 2017-07-13 at 08 08 37" src="https://user-images.githubusercontent.com/3206538/28152877-f8701764-67a2-11e7-89e6-9d7722a83f45.png">

(the red oval annotations are for highlighting the problem; they are not part of the plot).

I suspect it is an issue with the size of the nodes. I use size 10 for the inner nodes and the clipping issue goes away if I use half the size, but I would expect that a bounding box for a plot would take node size into account?

**Comment by thomasp85** [comment]
This is simply a resizing issue. The circles are of absolute size while the plot area is relative. This comes to show when you try to cram 4 plots into the same area :-)
