### ISSUE TITLE
Hierarchical Edge Budnles

### ISSUE THREAD

**Issue by Athanasiamo** [thomasp85/ggraph#8]
Hey.

Thanks for some really cool tools, hoping they can be of use for me. 

Been trying to understand the data structure needed to make the Hierarchical Edge Bundles map, but the flare data are just way too large to navigate. I can understand the purpose of flare$edges and flare$vertices, but I don't understand the purpose of flare$import . Could you maybe provide some more information about the data structure necessary for this plot?

Also, how is the naming of the edges and vertices indexed? I've tried this on my data (what I think is the correct structure at least for this part), but I keep getting this error: 
Some vertex names in edge list are not listed in vertex data frame.

![image](https://cloud.githubusercontent.com/assets/14014329/14148174/c8fe8fcc-f69e-11e5-8326-689e8b25c0be.png)

**Comment by thomasp85** [comment]
I'll try to see if I can address these questions adequately:

The hierarchical edge bundles uses a concept called connections; that is, links between edges that do not interfere with how the layout is calculate. A connection can be thought of as the sequence of nodes to travel through to get from the start to the end. In the flare example the class hierarchy makes up the graph structure which end up as a hierarchical layout (that isn't drawn). The import data is then a secondary structure that defines links between nodes in the hierarchy, but isn't part of that hierarchy. For the hierarchical edge bundles the paths defining the connections are detected automatically using the gCon function...

For the second question, this is more an igraph issue, and I suggest you consult the documentation (it's very well documented)

Hope this helps - I'm in the last stage of thesis writing at the moment, so it is a little short...

**Comment by shackett** [comment]
This was a really useful comment. I was having a hard time using geom_edge_bundle until I realized that flare$edges was a full rooted hierarchy (I only had specific and general classes, but nothing to connect the general classes). Good luck with your thesis!

**Comment by thomasp85** [comment]
Glad it made sense - feel free to get back with further questions. I'm planning on adding a wiki once time permits, but until then some of the specifics of the API can be a bit hard to grasp
