### ISSUE TITLE
using my own fixed coordinates

### ISSUE THREAD

**Issue by pachamaltese** [thomasp85/ggraph#80]
I'd like to re-arrange some nodes to avoid out-of-margins nodes legends

I'm doing this

```
tkid = tkplot(network) #tkid is the id of the tkplot that will open
l = tkplot.getcoords(tkid) # grab the coordinates from tkplot
ggraph(network, layout = l)
```

of course it says "unknown layout" as the documentation says but I'd like to pass my own coordinates

**Comment by thomasp85** [comment]
You will need to use the manual layout
