### ISSUE TITLE
Dendrogram layout fails with error "object 'direction' not found"

### ISSUE THREAD

**Issue by atheriel** [thomasp85/ggraph#81]
This is a more general version of the errors reported in #72 and #79.

The code (verbatim from several examples)

```r
fgraph <- igraph::graph_from_data_frame(flare$edges, vertices = flare$vertices)
ggraph(fgraph, layout = "dendrogram") +
  geom_edge_elbow()
```

fails with (as in #72):

    Error in eval(expr, envir, enclos) : object 'direction' not found

Passing e.g. `direction = "out"` in either `ggraph()` or in `geom_edge_elbow` itself yields the same error. Wrapping it in an `aes()` call, e.g.

```r
ggraph(fgraph, layout = "dendrogram") +
  geom_edge_elbow(aes(direction = "out"))
```

emits the warning (as in #79)

    Warning message:
    Removed 251 rows containing non-finite values (stat_edge_elbow).

and draws an empty plot.

**Comment by thomasp85** [comment]
Fixed in 36fc2a9
