### ISSUE TITLE
Plotting empty graph or graph without edges

### ISSUE THREAD

**Issue by clhunsen** [thomasp85/ggraph#82]
While using `ggraph` (current version on CRAN, R 3.3.1) for plotting my `igraph` graphs, I found that the plotting of empty graphs or graphs without edges results in an error (see below for an example). 

In my scripts, I heavily use `igraph::induced_subgraph` and it may happen that the induced subgraphs do not have edges. While checking for the error, I noticed that it also occurs if the given graph is completely empty (no vertices).

Is it possible to change `ggraph` to get an empty plotting pane when giving an empty graph or just plotting the nodes when there are no edges connecting them? 
Let me know if I can help somehow. And thank you for your nice work on this package.

### Example

```R
requireNamespace("igraph")
requireNamespace("gglot2")
requireNamespace("ggraph")

# g <- igraph::sample_pa(10, directed = TRUE) # works fine
# g <- igraph::make_empty_graph(n = 0, directed = FALSE) # no vertices, does not work
g <- igraph::make_empty_graph(n = 2, directed = FALSE) # no edges, does not work

VERTEX.SIZE <- 7
p <- ggraph::ggraph(g, layout = "nicely") +
    ggraph::geom_node_point(color = "red", size = VERTEX.SIZE) +
    ggraph::geom_edge_fan(
        end_cap = ggraph::circle(VERTEX.SIZE + 3, 'pt'),
        start_cap = ggraph::circle(VERTEX.SIZE + 3, 'pt'),
        arrow = if (igraph::is.directed(g)) {
            ggplot2::arrow(length = ggplot2::unit(VERTEX.SIZE / 2, 'pt'), ends = "last", type = "closed")
        } else {
            NULL
        }
    )
print(p)
```

The error I get is the following:
> \> p <- ggraph::ggraph(g, layout = "nicely") +
> \+     ggraph::geom_node_point(color = "red", size = VERTEX.SIZE) +
> \+     ggraph::geom_edge_link(
> \+         end_cap = ggraph::circle(VERTEX.SIZE + 3, 'pt'),
> \+         start_cap = ggraph::circle(VERTEX.SIZE + 3, 'pt')
> \+     )
> \> print(p)
> Error in `$<-.data.frame`(`*tmp*`, "circular", value = FALSE) : 
>   replacement has 1 row, data has 0

When I use the completely empty graph, I get the following error:

> \> p <- ggraph::ggraph(g, layout = "nicely") +
> \+     ggraph::geom_node_point(color = "red", size = VERTEX.SIZE) +
> \+     ggraph::geom_edge_link(
> \+         end_cap = ggraph::circle(VERTEX.SIZE + 3, 'pt'),
> \+         start_cap = ggraph::circle(VERTEX.SIZE + 3, 'pt')
> \+     )
> Error in `$<-.data.frame`(`*tmp*`, "circular", value = FALSE) : 
>   replacement has 1 row, data has 0
> \> print(p)
> Error in print(p) : object 'p' not found

### Side note on `igraph` behavior

I tried `igraph` to plot the graphs and it is able to plot an edgeless graph (try `igraph::plot.igraph(igraph::make_empty_graph(n = 2))`), although it also fails for the empty graph (`igraph::plot.igraph(igraph::make_empty_graph(n = 0))`).

**Comment by strohne** [comment]
I stumbled upon the same issue. The problem is still there in ggraph v1.0.2
