### ISSUE TITLE
support "tripartite" plots

### ISSUE THREAD

**Issue by maxheld83** [thomasp85/ggraph#83]
this is a fantastic package, I'm just starting to figure things out, so apologies in advance, if this is somehow ignorant.

I'd really like to use a tripartite plot. (We have data where 2 axes are sinks/source nodes only, and 1 axis is internal nodes only (the one in the middle) – so it seems like a tripartite extension of a bipartite plot would fit well.). 

My graph terminology is not quite developed, so I'm attaching a (bad) sketch to show what I mean.

![fullsizeoutput_d65](https://user-images.githubusercontent.com/5372770/29998650-2583c050-9031-11e7-9810-313b0f8a9cce.jpeg)

So far we're shoehorning our network into a hive plot, but it looks a little odd, and the arguments do not seem to allow us to tweak it into a parallel-axes layout (probably for good reasons).

Not sure how widespread this use case is, just thought I'd leave this here.

Such impressive work, thanks so much!

cc @verenakasztantowicz

**Comment by maxheld83** [comment]
we figured out another (better) way via non-simple graphs.

I'm going to leave this open in case anyone else finds this interesting.

**Comment by thomasp85** [comment]
should be possible with the new constraint features of the stress layout
