### ISSUE TITLE
allow using ggraph *without* attaching it

### ISSUE THREAD

**Issue by maxheld83** [thomasp85/ggraph#85]
```
library(ggraph)
library(igraph)
graph <- igraph::graph_from_data_frame(highschool)

# Not specifying the layout - defaults to "auto"
g <- ggraph(graph) + 
  geom_edge_link(aes(colour = factor(year))) + 
  geom_node_point()
g
```
This is fine:

![rplot](https://user-images.githubusercontent.com/5372770/30227310-82bddee8-94d9-11e7-85e6-d86f8977efc9.png)

However, when plotted without `ggraph` attached, the legend is missing and there are different colors.

```
detach(name = "package:ggraph", unload = TRUE)
g  # without legend
```

![rplot01](https://user-images.githubusercontent.com/5372770/30227696-d8070482-94da-11e7-8393-24bbbb1ec844.png)

I am (wildly) guessing this has something to do with the black magic of the edge aesthetics that `ggraph` does.

This is not a problem in a script use (where usually you'd have `library(ggraph)`), but it can be a little odd in in-package use:
I'd rather not import the entire `ggraph` namespace, but *without* that, my examples on `ggraph`-derivative functions will not work properly (as in the above).

The behavior also strikes me as a little unexpected because, `class(g)` is only `"gg"     "ggplot"`, which makes me think that *just* `ggplot::print.ggplot()` ought to do the trick.

Is there any chance this could be changed?

**Comment by thomasp85** [comment]
This is unfortunately outside the hands of ggraph. It all boils down to how ggplot2 itself handles guides and legends. Currently it is looking on the search path for functions of the right name so you'll need to import these from ggraph in order to get it to work... hopefully the guide system will get an overhaul and adopt the ggproto approach someday, but as I said this is ggplot2 stuff, not ggraph

**Comment by maxheld83** [comment]
thanks so much for clarifying!

Do you have any recommendation for how to go about this if `ggraph` is used inside a package?

I have an `autoplot` method that uses `ggraph`, and I don't want to `Imports: ggraph` in the `DESCRIPTION`, because it's a rare use case.

So for now, I just remind users to `library(ggraph)` when they use this particular `autoplot` method.
